# How to use PyEPISuite
TODO: explain the installation procedure

## Call EPISuite for a list of CAS numbers

In [4]:
from pyepisuite.utils import (
    search_episuite,
    search_episuite_by_cas,
    submit_to_episuite,
    json_to_episuite,
    json_to_ecosar,
)
from pyepisuite.api_client import EpiSuiteAPIClient
from pyepisuite.expdata import (
    HenryData,
    BoilingPointData,
    VaporPressureData,
    MeltingPointData,
    SolubilityData,
)

In [5]:
cas_list = ["50-00-0", "100-00-5", "100-02-7", "111-65-9"]
ids = search_episuite_by_cas(cas_list)
ids

[Identifiers(name='FORMALDEHYDE', smiles='O=C', cas='000050-00-0'),
 Identifiers(name='P-CHLORONITROBENZENE', smiles='N(=O)(=O)c(ccc(c1)Cl)c1', cas='000100-00-5'),
 Identifiers(name='4-NITROPHENOL', smiles='N(=O)(=O)c(ccc(O)c1)c1', cas='000100-02-7'),
 Identifiers(name='OCTANE', smiles='C(CCCCCC)C', cas='000111-65-9')]

In [6]:
search_episuite(["N(=O)(=O)c(ccc(c1)Cl)c1"])

[Identifiers(name=None, smiles='N(=O)(=O)c(ccc(c1)Cl)c1', cas=None),
 Identifiers(name='P-CHLORONITROBENZENE', smiles='N(=O)(=O)c(ccc(c1)Cl)c1', cas='000100-00-5'),
 Identifiers(name='Benzene-1,2,4,5-d4, 3-chloro-6-nitro-', smiles='Clc1ccc(cc1)N(=O)(=O)', cas='068239-23-6')]

In [7]:
epi_result, ecosar_result = submit_to_episuite(ids)
epi_result

[ResultEPISuite(parameters=Parameters(cas='000050-00-0', smiles=None, caseNumber=None, userLogKow=Parameter(value=-999.0, units='', valueType='USER_PROVIDED'), userMeltingPoint=Parameter(value=-999.0, units='celsius', valueType='USER_PROVIDED'), userBoilingPoint=Parameter(value=-999.0, units='celsius', valueType='USER_PROVIDED'), userWaterSolubility=Parameter(value=-999.0, units='mg/L', valueType='USER_PROVIDED'), userVaporPressure=Parameter(value=-999.0, units='mmHg', valueType='USER_PROVIDED'), userHenrysLawConstant=Parameter(value=-999.0, units='atm-m3/mol', valueType='USER_PROVIDED'), userLogKoa=Parameter(value=-999.0, units='', valueType='USER_PROVIDED'), userLogKoc=Parameter(value=-999.0, units='L/kg', valueType='USER_PROVIDED'), userHydroxylReactionRateConstant=Parameter(value=-999.0, units='cm3/molecule-sec', valueType='USER_PROVIDED'), userDermalPermeabilityCoefficient=Parameter(value=-999.0, units='cm/hr', valueType='USER_PROVIDED'), userBiodegradationRateRemoveMetals=Parameter(value=True, units='boolean', valueType='USER_PROVIDED'), userAtmosphericHydroxylRadicalConcentration=Parameter(value=1500000.0, units='radicals/cm3', valueType='USER_PROVIDED'), userAtmosphericOzoneConcentration=Parameter(value=700000000000.0, units='molecules/cm3', valueType='USER_PROVIDED'), userAtmosphericDaylightHours=Parameter(value=12.0, units='hours', valueType='USER_PROVIDED'), userStpHalfLifePrimaryClarifier=Parameter(value=10000.0, units='hours', valueType='USER_PROVIDED'), userStpHalfLifeAerationVessel=Parameter(value=10000.0, units='hours', valueType='USER_PROVIDED'), userStpHalfLifeSettlingTank=Parameter(value=10000.0, units='hours', valueType='USER_PROVIDED'), userFugacityHalfLifeAir=Parameter(value=0.0, units='hours', valueType='USER_PROVIDED'), userFugacityHalfLifeWater=Parameter(value=0.0, units='hours', valueType='USER_PROVIDED'), userFugacityHalfLifeSoil=Parameter(value=0.0, units='hours', valueType='USER_PROVIDED'), userFugacityHalfLifeSediment=Parameter(value=0.0, units='hours', valueType='USER_PROVIDED'), userFugacityEmissionRateAir=Parameter(value=1000.0, units='kg/hour', valueType='USER_PROVIDED'), userFugacityEmissionRateWater=Parameter(value=1000.0, units='kg/hour', valueType='USER_PROVIDED'), userFugacityEmissionRateSoil=Parameter(value=1000.0, units='kg/hour', valueType='USER_PROVIDED'), userFugacityEmissionRateSediment=Parameter(value=0.0, units='kg/hour', valueType='USER_PROVIDED'), userFugacityAdvectionTimeAir=Parameter(value=100.0, units='hours', valueType='USER_PROVIDED'), userFugacityAdvectionTimeWater=Parameter(value=1000.0, units='hours', valueType='USER_PROVIDED'), userFugacityAdvectionTimeSoil=Parameter(value=0.0, units='hours', valueType='USER_PROVIDED'), userFugacityAdvectionTimeSediment=Parameter(value=50000.0, units='hours', valueType='USER_PROVIDED'), modules=[]), chemicalProperties=ChemicalProperties(name='FORMALDEHYDE', systematicName='Formaldehyde', cas='000050-00-0', smiles='C=O', molecularWeight=30.026022332008978, molecularFormula='CH2O', molecularFormulaHtml='CH<sub>2</sub>O', organic=True, organicAcid=False, aminoAcid=False, nonStandardMetal=False, flags=None), logKow=LogKowResponse(estimatedValue=logKowEstimatedValue(model=KowModel(logKow=0.3500000014901161, factors=[KowFactor(type='Fragment', description='Formaldehyde experimental value - constant', fragmentCount=1, coefficient=0.12099999934434891, contribution=0.12099999934434891, trainingCount=1, validationCount=0), KowFactor(type='Constant', description='Equation Constant', fragmentCount=0, coefficient=0.0, contribution=0.2290000021457672, trainingCount=0, validationCount=0)], output='-------+-----+--------------------------------------------+---------+--------\n TYPE  | NUM |        LOGKOW FRAGMENT DESCRIPTION         |  COEFF  |  VALUE \n-------+-----+--------------------------------------------+---------+--------\n Frag  |  1  |  Formaldehyde experimental value - constant| 0.1210  |  0.1210\n Const |     |  Equation Constant                         |         |  0.2290\n-------+-----+--------------------------------------------+---------+--------\n                                                         Log Kow   =   0.3500\n', notes='', flags=Flag(isOrganicAcid=False, isAminoAcid=False)), value=0.3500000014901161, units='', valueType='ESTIMATED'), experimentalValues=[ExperimentalValue(author='HANSCH,C ET AL.', year=1995, order=1, value=0.35, units=None, valueType='EXPERIMENTAL')], selectedValue=SelectedValue(value=0.35, units=None, valueType='EXPERIMENTAL')), meltingPoint=MeltingPointResponse(estimatedValue=MeltingPointEstimatedValue(model=MeltingPointModel(factors=[MeltingPointFactor(type='Group', description='-CHO (aldehyde)', fragmentCount=1, coefficient=36.900001525878906, totalCoefficient=36.900001525878906), MeltingPointFactor(type='*', description='Equation Constant', fragmentCount=0, coefficient=122.5, totalCoefficient=122.5)], meltingPointKelvins=159.39999389648438, meltingPointLimitKelvins=159.39999389648438, meltingPointCelsius=-113.760009765625, meltingPointAdaptedJoback=-113.760009765625, meltingPointGoldOgle=-108.11260986328125, meltingPointMean=-110.93630981445312, meltingPointSelected=-110.93630981445312), value=-110.93630981445312, units='celsius', valueType='ESTIMATED'), experimentalValues=[ExperimentalValue(author='ZHOU,X & MOPPER,K', year=1990, order=1, value=-92.0, units='celsius', valueType='EXPERIMENTAL')], selectedValue=SelectedValue(value=-92.0, units='celsius', valueType='EXPERIMENTAL')), boilingPoint=BoilingPointResponse(estimatedValue=BoilingPointEstimatedValue(model=BoilingPointModel(factors=[BoilingPointFactor(type='Group', description='-CHO (aldehyde)', fragmentCount=1, coefficient=83.37999725341797, totalCoefficient=83.37999725341797), BoilingPointFactor(type='*', description='Equation Constant', fragmentCount=0, coefficient=0.0, totalCoefficient=198.17999267578125)], boilingPointKelvinsUncorrected=281.55999755859375, boilingPointKelvinsCorrected=282.663818359375, boilingPointCelsius=9.503814697265625), value=9.503814697265625, units='celsius', valueType='ESTIMATED'), experimentalValues=[ExperimentalValue(author=None, year=0, order=1, value=-19.5, units='celsius', valueType='EXPERIMENTAL')], selectedValue=SelectedValue(value=-19.5, units='celsius', valueType='EXPERIMENTAL')), vaporPressure=VaporPressureResponse(estimatedValue=VaporPressureEstimatedValue(model=[VaporPressureModelItem(type='Antoine', mmHg=3723.386962890625, pa=496409.3966665039), VaporPressureModelItem(type='Grain', mmHg=3347.14019704179, pa=446247.42535000556), VaporPressureModelItem(type='Mackay', mmHg=3033.353870111578, pa=404412.8046710158), VaporPressureModelItem(type='Selected', mmHg=3535.2635799662075, pa=471328.41100825474), VaporPressureModelItem(type='SubCooled', mmHg=3347.14013671875, pa=446247.4173076172)], value=3535.2635799662075, units='mmHg', valueType='ESTIMATED'), experimentalValues=[ExperimentalValue(author='BOUBLIK,T ET AL.', year=1984, order=1, value=3890.0, units='mmHg', valueType='EXPERIMENTAL')], selectedValue=SelectedValue(value=3890.0, units='mmHg', valueType='EXPERIMENTAL')), waterSolubilityFromLogKow=WaterSolubilityFromLogKowResponse(parameters=WaterSolubilityFromLogKowParameters(smiles='C=O', cas='000050-00-0', logKow=Parameter(value=0.35, units=None, valueType='EXPERIMENTAL'), meltingPoint=Parameter(value=-92.0, units='celsius', valueType='EXPERIMENTAL')), estimatedValue=WaterSolubilityEstimatedValue(model=WaterSolubilityModel(waterSolubility=54982.12109375, factors=[WaterSolubilityFromLogKowFactor(type='No Applicable Correction Factors', description=None, fragmentCount=1, coefficient=0.0, totalCoefficient=0.0, trainingCount=0, maxFragmentCount=0)], equation='Log S (mol/L) = 0.693-0.96 log Kow-0.0092(Tm-25)-0.00314 MW + Correction\n Melting Pt (Tm) = -92.0 deg C (Use Tm = 25 for all liquids)\nUser Entered Melting Point: -92.0', notes='', output='MOL FOR: C1 H2 O1 \nMOL WT : 30.03\nLog Kow (experimental):  0.35\nLog Kow used by Water solubility estimates:  0.35 (user entered)\n\nEquation Used to Make Water Sol estimate:\n   Log S (mol/L) = 0.693-0.96 log Kow-0.0092(Tm-25)-0.00314 MW + Correction\n\n      Melting Pt (Tm) = -92.00 deg C (Use Tm = 25 for all liquids)\n\n      Correction(s):         Value\n      --------------------   -----\n       No Applicable Correction Factors\n\n   Log Water Solubility  (in moles/L) :  0.263\n   Water Solubility at 25 deg C (mg/L):  5.498e+04\n'), value=54982.12109375, units='mg/L', valueType='ESTIMATED'), experimentalValues=[], selectedValue=SelectedValue(value=54982.12109375, units='mg/L', valueType='ESTIMATED')), waterSolubilityFromWaterNt=WaterSolubilityFromWaterNtResponse(parameters=WaterSolubilityFromWaterNtParameters(smiles='C=O', cas='000050-00-0'), estimatedValue=WaterSolubilityFromWaterNtEstimatedValue(model=WaterSolubilityFromWaterNtModel(waterSolubility=396938.21875, factors=[WaterSolubilityFromWaterNtFactor(type='Fragment', description='Formaldehyde experimental value - constant', fragmentCount=1, coefficient=0.871999979019165, totalCoefficient=0.871999979019165, trainingCount=2, maxFragmentCount=2), WaterSolubilityFromWaterNtFactor(type='Constant', description='Equation Constant', fragmentCount=1, coefficient=0.24921822547912598, totalCoefficient=0.24921822547912598, trainingCount=0, maxFragmentCount=0)], equation='', notes='', output='MOL FOR: C1 H2 O1 \nMOL WT : 30.03\n-------+-----+--------------------------------------------+----------+---------\n TYPE  | NUM |    WATER SOLUBILITY FRAGMENT DESCRIPTION   |  COEFF   |  VALUE  \n-------+-----+--------------------------------------------+----------+---------\n Frag  |  1  |  Formaldehyde experimental value - constant| 0.8720   |  0.8720\n Const |     |  Equation Constant                         |          |  0.2492\n-------+-----+--------------------------------------------+----------+---------\n                              Log Water Sol (moles/L) at 25 dec C  =    1.1212\n                              Water Solubility (mg/L) at 25 dec C  =3.9694e+05\n'), value=396938.21875, units='mg/L', valueType='ESTIMATED'), experimentalValues=[], selectedValue=SelectedValue(value=396938.21875, units='mg/L', valueType='ESTIMATED')), henrysLawConstant=HenrysLawConstantResponse(parameters=HenrysLawConstantParameters(smiles='C=O', cas='000050-00-0', waterSolubility=Parameter(value=54982.12109375, units='mg/L', valueType='ESTIMATED'), vaporPressure=Parameter(value=760.0, units='mmHg', valueType='EXPERIMENTAL'), molecularWeight=Parameter(value=30.026022332008978, units='g/mol', valueType='NONE')), estimatedValue=HenrysLawConstantEstimatedValue(model=[HenrysLawConstantModelItem(name='VP/WSOL', value=0.0005461925785725243, factors=None, hlcAtm=0.0005461925785725243, hlcUnitless=0.022325099775020223, hlcPaMol=55.342963023861074, notes=''), HenrysLawConstantModelItem(name='Bond', value=2.4205780029296875, factors=[HenrysLawConstantFactor(type='Hydrogen', description='Hydrogen to Carbonyl (C=O) Bonds', fragmentCount=2, totalCoefficient=2.4205780029296875, trainingCount=25, maxFragmentCount=1)], hlcAtm=9.287064312957227e-05, hlcUnitless=0.003796837292611599, hlcPaMol=9.410118103027344, notes=''), HenrysLawConstantModelItem(name='Group', value=2.5999999046325684, factors=[HenrysLawConstantFactor(type='NONE    ', description='H2CO', fragmentCount=1, totalCoefficient=2.5999999046325684, trainingCount=0, maxFragmentCount=0)], hlcAtm=6.144075450720266e-05, hlcUnitless=0.00251188687980175, hlcPaMol=6.225484371185303, notes='')], value=6.144075450720266e-05, units='atm-m3/mol', valueType='ESTIMATED'), experimentalValues=[ExperimentalValue(author='BETTERTON,EA & HOFFMAN,MR', year=1988, order=1, value=3.37e-07, units='atm-m3/mol', valueType='EXPERIMENTAL')], selectedValue=SelectedValue(value=3.37e-07, units='atm-m3/mol', valueType='EXPERIMENTAL')), logKoa=LogKoaResponse(parameters=LogKoaParameters(smiles='C=O', cas='000050-00-0', logKow=Parameter(value=0.35, units=None, valueType='EXPERIMENTAL'), henrysLawConstant=Parameter(value=3.37e-07, units='atm-m3/mol', valueType='EXPERIMENTAL')), estimatedValue=LogKoaEstimatedValue(model=LogKoaModel(kow=2.2387211385683394, kaw=1.3774553004445097e-05, koa=162525.86474827142, logKoa=5.210922485460039), value=5.210922485460039, units='', valueType='ESTIMATED'), experimentalValues=[], selectedValue=SelectedValue(value=5.210922485460039, units='', valueType='ESTIMATED')), biodegradationRate=BiodegradationRateResponse(parameters=BiodegradationRateParameters(smiles='C=O', cas='000050-00-0', removeMetals=True), models=[BiodegradationRateModel(name='Linear Model Prediction', value=1.0178809966892004, factors=[BiodegradationRateFactor(type='Fragment', description='Aldehyde   [-CHO]', fragmentCount=1, coefficient=0.2846300005912781, totalCoefficient=0.2846300005912781, trainingCount=4, maxFragmentCount=1), BiodegradationRateFactor(type='Molecular Weight', description='Molecular Weight Parameter', fragmentCount=0, coefficient=0.0, totalCoefficient=-0.014294842258095741, trainingCount=0, maxFragmentCount=0), BiodegradationRateFactor(type='Constant', description='Equation Constant', fragmentCount=0, coefficient=0.0, totalCoefficient=0.7475458383560181, trainingCount=0, maxFragmentCount=0)]), BiodegradationRateModel(name='Non-Linear Model Prediction', value=0.9999424456671815, factors=[BiodegradationRateFactor(type='Fragment', description='Aldehyde   [-CHO]', fragmentCount=1, coefficient=7.1803998947143555, totalCoefficient=7.1803998947143555, trainingCount=4, maxFragmentCount=1), BiodegradationRateFactor(type='Molecular Weight', description='Molecular Weight Parameter', fragmentCount=0, coefficient=0.0, totalCoefficient=-0.4263763129711151, trainingCount=0, maxFragmentCount=0)]), BiodegradationRateModel(name='Ultimate Biodegradation Timeframe', value=3.1551359500736, factors=[BiodegradationRateFactor(type='Fragment', description='Aldehyde   [-CHO]', fragmentCount=1, coefficient=0.02232000045478344, totalCoefficient=0.02232000045478344, trainingCount=5, maxFragmentCount=1), BiodegradationRateFactor(type='Molecular Weight', description='Molecular Weight Parameter', fragmentCount=0, coefficient=0.0, totalCoefficient=-0.06635463982820511, trainingCount=0, maxFragmentCount=0), BiodegradationRateFactor(type='Constant', description='Equation Constant', fragmentCount=0, coefficient=0.0, totalCoefficient=3.1991705894470215, trainingCount=0, maxFragmentCount=0)]), BiodegradationRateModel(name='Primary Biodegradation Timeframe', value=4.001056153327227, factors=[BiodegradationRateFactor(type='Fragment', description='Aldehyde   [-CHO]', fragmentCount=1, coefficient=0.1966399997472763, totalCoefficient=0.1966399997472763, trainingCount=5, maxFragmentCount=1), BiodegradationRateFactor(type='Molecular Weight', description='Molecular Weight Parameter', fragmentCount=0, coefficient=0.0, totalCoefficient=-0.0433209203183651, trainingCount=0, maxFragmentCount=0), BiodegradationRateFactor(type='Constant', description='Equation Constant', fragmentCount=0, coefficient=0.0, totalCoefficient=3.8477370738983154, trainingCount=0, maxFragmentCount=0)]), BiodegradationRateModel(name='MITI Linear Model Prediction', value=0.7393221855163574, factors=[BiodegradationRateFactor(type='Fragment', description='Aldehyde   [-CHO]', fragmentCount=1, coefficient=0.23229999840259552, totalCoefficient=0.23229999840259552, trainingCount=23, maxFragmentCount=2), BiodegradationRateFactor(type='Molecular Weight', description='Molecular Weight Parameter', fragmentCount=0, coefficient=0.0, totalCoefficient=-0.04735179245471954, trainingCount=0, maxFragmentCount=0), BiodegradationRateFactor(type='Constant', description='Equation Constant', fragmentCount=0, coefficient=0.0, totalCoefficient=0.5543739795684814, trainingCount=0, maxFragmentCount=0)]), BiodegradationRateModel(name='MITI Non-Linear Model Prediction', value=0.8870785940134347, factors=[BiodegradationRateFactor(type='Fragment', description='Aldehyde   [-CHO]', fragmentCount=1, coefficient=0.9184100031852722, totalCoefficient=0.9184100031852722, trainingCount=23, maxFragmentCount=2), BiodegradationRateFactor(type='Molecular Weight', description='Molecular Weight Parameter', fragmentCount=0, coefficient=0.0, totalCoefficient=-0.5194584727287292, trainingCount=0, maxFragmentCount=0)]), BiodegradationRateModel(name='Anaerobic Model Prediction', value=0.9586509242653847, factors=[BiodegradationRateFactor(type='Fragment', description='Aldehyde   [-CHO]', fragmentCount=1, coefficient=0.12256655842065811, totalCoefficient=0.12256655842065811, trainingCount=5, maxFragmentCount=1), BiodegradationRateFactor(type='Constant', description='Equation Constant', fragmentCount=0, coefficient=0.0, totalCoefficient=0.8360843658447266, trainingCount=0, maxFragmentCount=0)])], notes='', output='SMILES : O=C\nMOL FOR: C1 H2 O1 \nMOL WT : 30.03\n--------------------------- BIOWIN v4.10 Results ----------------------------\n\n   Biowin1 (Linear Model Prediction)    :  Biodegrades Fast\n   Biowin2 (Non-Linear Model Prediction):  Biodegrades Fast\n   Biowin3 (Ultimate Biodegradation Timeframe):  Weeks\n   Biowin4 (Primary  Biodegradation Timeframe):  Days\n   Biowin5 (MITI Linear Model Prediction)    :  Readily Degradable\n   Biowin6 (MITI Non-Linear Model Prediction):  Readily Degradable\n   Biowin7 (Anaerobic Model Prediction):  Biodegrades Fast\n   Ready Biodegradability Prediction:  YES\n\n------+-----+--------------------------------------------+---------+---------\n TYPE | NUM |       Biowin1 FRAGMENT DESCRIPTION         |  COEFF  |  VALUE  \n------+-----+--------------------------------------------+---------+---------\n Frag |  1  |  Aldehyde   [-CHO]                         |  0.2846 |  0.2846\n MolWt|  *  |  Molecular Weight Parameter                |         | -0.0143\n Const|  *  |  Equation Constant                         |         |  0.7475\n============+============================================+=========+=========\n   RESULT   |    Biowin1 (Linear Biodeg Probability)     |         |  1.0179\n============+============================================+=========+=========\n\n------+-----+--------------------------------------------+---------+---------\n TYPE | NUM |       Biowin2 FRAGMENT DESCRIPTION         |  COEFF  |  VALUE  \n------+-----+--------------------------------------------+---------+---------\n Frag |  1  |  Aldehyde   [-CHO]                         |  7.1804 |  7.1804\n MolWt|  *  |  Molecular Weight Parameter                |         | -0.4264\n============+============================================+=========+=========\n   RESULT   |  Biowin2 (Non-Linear Biodeg Probability)   |         |  0.9999\n============+============================================+=========+=========\n\n A Probability Greater Than or Equal to 0.5 indicates --> Biodegrades Fast\n A Probability Less Than 0.5 indicates --> Does NOT Biodegrade Fast\n\n------+-----+--------------------------------------------+---------+---------\n TYPE | NUM |       Biowin3 FRAGMENT DESCRIPTION         |  COEFF  |  VALUE  \n------+-----+--------------------------------------------+---------+---------\n Frag |  1  |  Aldehyde   [-CHO]                         |  0.0223 |  0.0223\n MolWt|  *  |  Molecular Weight Parameter                |         | -0.0664\n Const|  *  |  Equation Constant                         |         |  3.1992\n============+============================================+=========+=========\n   RESULT   |  Biowin3 (Survey Model - Ultimate Biodeg)  |         |  3.1551\n============+============================================+=========+=========\n\n------+-----+--------------------------------------------+---------+---------\n TYPE | NUM |       Biowin4 FRAGMENT DESCRIPTION         |  COEFF  |  VALUE  \n------+-----+--------------------------------------------+---------+---------\n Frag |  1  |  Aldehyde   [-CHO]                         |  0.1966 |  0.1966\n MolWt|  *  |  Molecular Weight Parameter                |      

# The result class
The result class contains subclasses with both `estimatedValue` and `selectedValue` for each parameter. Some extra information can also be obtained from subclasses including references, and model parameters. In the following cell, I show some of these parameters and how to obtain them.

In [ ]:
# chemicalProperties
epi_result[0].chemicalProperties.cas
epi_result[0].chemicalProperties.smiles
epi_result[0].chemicalProperties.name
epi_result[0].chemicalProperties.molecularFormula
epi_result[0].chemicalProperties.systematicName
epi_result[0].chemicalProperties.molecularWeight
epi_result[0].chemicalProperties.organic
epi_result[0].chemicalProperties.organicAcid
epi_result[0].chemicalProperties.nonStandardMetal
epi_result[0].chemicalProperties.aminoAcid

# logKow
exp_logKow = []
epi_result[0].logKow.estimatedValue.value
epi_result[0].logKow.estimatedValue.units
for exp_class in epi_result[0].logKow.experimentalValues:
    exp_logKow.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# meltingPoint
exp_meltingPoint = []
epi_result[0].meltingPoint.estimatedValue.value
epi_result[0].meltingPoint.estimatedValue.units
for exp_class in epi_result[0].meltingPoint.experimentalValues:
    exp_meltingPoint.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })


# boilingPoint
exp_boilingPoint = []
epi_result[0].boilingPoint.estimatedValue.value
epi_result[0].boilingPoint.estimatedValue.units
for exp_class in epi_result[0].boilingPoint.experimentalValues:
    exp_boilingPoint.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# vaporPressure
exp_vaporPressure = []
epi_result[0].vaporPressure.estimatedValue.value
epi_result[0].vaporPressure.estimatedValue.units
for exp_class in epi_result[0].vaporPressure.experimentalValues:
    exp_vaporPressure.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# waterSolubilityFromLogKow
exp_waterSolubilityFromLogKow = []
epi_result[0].waterSolubilityFromLogKow.estimatedValue.value
epi_result[0].waterSolubilityFromLogKow.estimatedValue.units
for exp_class in epi_result[0].waterSolubilityFromLogKow.experimentalValues:
    exp_waterSolubilityFromLogKow.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# waterSolubilityFromWaterNt
exp_waterSolubilityFromWaterNt = []
epi_result[0].waterSolubilityFromWaterNt.estimatedValue.value
epi_result[0].waterSolubilityFromWaterNt.estimatedValue.units
for exp_class in epi_result[0].waterSolubilityFromWaterNt.experimentalValues:
    exp_waterSolubilityFromWaterNt.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# henrysLawConstant
exp_henrysLawConstant = []
epi_result[0].henrysLawConstant.estimatedValue.value
epi_result[0].henrysLawConstant.estimatedValue.units
for exp_class in epi_result[0].henrysLawConstant.experimentalValues:
    exp_henrysLawConstant.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# logKoa
exp_logKoa = []
epi_result[0].logKoa.estimatedValue.value
epi_result[0].logKoa.estimatedValue.units
for exp_class in epi_result[0].logKoa.experimentalValues:
    exp_logKoa.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# biodegradationRate
# there are 7 models:
# Linear Model Prediction
# Non-Linear Model Prediction
# Ultimate Biodegradation Timeframe
# Primary Biodegradation Timeframe
# MITI Linear Model Prediction
# MITI Non-Linear Model Prediction
# Anaerobic Model Prediction
# each model can be reached from the list of models epi_result[0].biodegradationRate.models
# by epi_result[0].biodegradationRate.models[0].name and .value

for model_class in epi_result[0].biodegradationRate.models:
    # print(model_class.name)
    # print(model_class.value)
    ...

# hydrocarbonBiodegradationRate
epi_result[0].hydrocarbonBiodegradationRate.estimatedValue.value
epi_result[0].hydrocarbonBiodegradationRate.estimatedValue.units

# aerosolAdsorptionFraction
epi_result[0].aerosolAdsorptionFraction.estimatedValue.value
epi_result[0].aerosolAdsorptionFraction.estimatedValue.units
epi_result[0].aerosolAdsorptionFraction.selectedValue.value
epi_result[0].aerosolAdsorptionFraction.selectedValue.units

# atmosphericHalfLife
epi_result[0].atmosphericHalfLife.estimatedValue.value
epi_result[0].atmosphericHalfLife.estimatedValue.units
epi_result[0].atmosphericHalfLife.estimatedHydroxylRadicalReactionRateConstant.value
epi_result[0].atmosphericHalfLife.estimatedHydroxylRadicalReactionRateConstant.units
epi_result[0].atmosphericHalfLife.estimatedOzoneReactionRateConstant.value
epi_result[0].atmosphericHalfLife.estimatedOzoneReactionRateConstant.units
exp_radical = []
for exp_class in epi_result[0].atmosphericHalfLife.experimentalHydroxylRadicalReactionRateConstantValues:
    exp_radical.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

exp_ozone = []
for exp_class in epi_result[0].atmosphericHalfLife.experimentalOzoneReactionRateConstantValues:
    exp_ozone.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# logKoc
epi_result[0].logKoc.estimatedValue.value
epi_result[0].logKoc.estimatedValue.units
exp_logKoc = []
for exp_class in epi_result[0].logKoc.experimentalValues:
    exp_logKoc.append({
        "value": exp_class.value,
        "units": exp_class.units,
        "reference": f"{exp_class.author}, {exp_class.year}"
    })

# hydrolysis
epi_result[0].hydrolysis.acidCatalyzedRateConstant
epi_result[0].hydrolysis.baseCatalyzedRateConstant
epi_result[0].hydrolysis.neutralRateConstant
epi_result[0].hydrolysis.acidCatalyzedRateConstantForTransIsomer

phosphor_half_live = []
for exp_class in epi_result[0].hydrolysis.halfLives:
    phosphor_half_live.append({
        "value": exp_class.value,
        "pH": exp_class.ph,
        "unit": exp_class.unit,
        "acid_catalyzed": exp_class.acidCatalyzed,
        "base_catalyzed": exp_class.baseCatalyzed,
        "neutral": exp_class.isomer,
        "phosphor_ester": exp_class.phosphorusEster
    })

# bioconcentration
epi_result[0].bioconcentration.bioaccumulationFactor
epi_result[0].bioconcentration.bioconcentrationFactor
epi_result[0].bioconcentration.biotransformationHalfLife
epi_result[0].bioconcentration.experimentalBioTransformationRate
# there is a list of arnotGobasBcfBafEstimates each one for a different trophic level
epi_result[0].bioconcentration.arnotGobasBcfBafEstimates[0].trophicLevel
epi_result[0].bioconcentration.arnotGobasBcfBafEstimates[0].bioaccumulationFactor
epi_result[0].bioconcentration.arnotGobasBcfBafEstimates[0].bioconcentrationFactor
epi_result[0].bioconcentration.arnotGobasBcfBafEstimates[0].unit

# waterVolatilization
epi_result[0].waterVolatilization.lakeHalfLifeHours
epi_result[0].waterVolatilization.riverHalfLifeHours
epi_result[0].waterVolatilization.parameters.lakeCurrentVelocityMetersPerSecond
epi_result[0].waterVolatilization.parameters.lakeWaterDepthMeters
epi_result[0].waterVolatilization.parameters.lakeWindVelocityMetersPerSecond
epi_result[0].waterVolatilization.parameters.riverCurrentVelocityMetersPerSecond
epi_result[0].waterVolatilization.parameters.riverWaterDepthMeters
epi_result[0].waterVolatilization.parameters.riverWindVelocityMetersPerSecond

# sewageTreatmentModel
# it has many parameters under epi_result[0].sewageTreatmentModel.model
# SewageModelComponents(Influent=SewageModelComponent(MassPerHour=10.0, MolPerHour=0.3330444395542145, Percent=100.0), PrimarySludge=SewageModelComponent(MassPerHour=0.02548598105480249, MolPerHour=0.0008487964569853235, Percent=0.2548598193446651), WasteSludge=SewageModelComponent(MassPerHour=0.1508191430534572, MolPerHour=0.005022947870598627, Percent=1.5081914825907095), TotalSludge=SewageModelComponent(MassPerHour=0.1763051241082597, MolPerHour=0.00587174432758395, Percent=1.7630513019353746), PrimVloitilization=SewageModelComponent(MassPerHour=0.000183429636301717, MolPerHour=6.109022252830457e-06, Percent=0.00183429636301717), SettlingVloitilization=SewageModelComponent(MassPerHour=0.0004997904536773821, MolPerHour=1.6645243728473646e-05, Percent=0.004997904536773821), AerationOffGas=SewageModelComponent(MassPerHour=0.00123325135741045, MolPerHour=4.107275213347454e-05, Percent=0.01233251399976865), TotalAir=SewageModelComponent(MassPerHour=0.0019164714473895491, MolPerHour=6.382701811477865e-05, Percent=0.01916471489955964), PrimBiodeg=SewageModelComponent(MassPerHour=0.00175920009021307, MolPerHour=5.8589182833114484e-05, Percent=0.0175920009021307), SettlingBiodeg=SewageModelComponent(MassPerHour=0.0005268808643572535, MolPerHour=1.7547474823831824e-05, Percent=0.0052688086435725345), AerationBiodeg=SewageModelComponent(MassPerHour=0.006938053585300231, MolPerHour=0.00023106802476679445, Percent=0.0693805358530023), TotalBiodeg=SewageModelComponent(MassPerHour=0.009224134539870555, MolPerHour=0.0003072046824237408, Percent=0.09224134539870553), FinalEffluent=SewageModelComponent(MassPerHour=9.812553863376403, MolPerHour=0.32680166148212986, Percent=98.12554202062623), TotalRemoval=SewageModelComponent(MassPerHour=0.18744613662359733, MolPerHour=0.00624277807208462, Percent=1.8744613662359733), PrimaryRateConstant=SewageModelComponent(MassPerHour=0.0278394166380167, MolPerHour=24.892763137817383, Percent=10000.0), AerationRateConstant=SewageModelComponent(MassPerHour=0.0278394166380167, MolPerHour=24.892763137817383, Percent=10000.0), SettlingRateConstant=SewageModelComponent(MassPerHour=0.0278394166380167, MolPerHour=24.892763137817383, Percent=10000.0))

# fugacityModel
# halflife in air, water, soil, and sediment in an array in unit hours
epi_result[0].fugacityModel.model.HalfLifeArray

# dermalPermeability
epi_result[0].dermalPermeability.dermalPermeabilityCoefficient
epi_result[0].dermalPermeability.dermalAbsorbedDosePerEvent
epi_result[0].dermalPermeability.lagTimePerEventHours
epi_result[0].dermalPermeability.dermalAbsorbedDose
epi_result[0].dermalPermeability.timeToReachSteadyStateHours

# analogs
# analog casrn list
# epi_result[0].analogs

# logKowAnalogs

0.0018156810226975285

In [11]:
epi_result[0].biodegradationRate.models[0].name

'Linear Model Prediction'

In [88]:
epi_result[0].hydrolysis.halfLives

[HydrolysisHalfLife(ph=7.0, value=0.0, unit=None, baseCatalyzed=True, acidCatalyzed=False, phosphorusEster=False, isomer=None),
 HydrolysisHalfLife(ph=7.0, value=0.0, unit=None, baseCatalyzed=False, acidCatalyzed=True, phosphorusEster=False, isomer=None),
 HydrolysisHalfLife(ph=7.0, value=0.0, unit=None, baseCatalyzed=False, acidCatalyzed=False, phosphorusEster=False, isomer=None),
 HydrolysisHalfLife(ph=7.0, value=0.0, unit=None, baseCatalyzed=False, acidCatalyzed=True, phosphorusEster=True, isomer=None),
 HydrolysisHalfLife(ph=7.0, value=0.0, unit=None, baseCatalyzed=False, acidCatalyzed=True, phosphorusEster=False, isomer=None),
 HydrolysisHalfLife(ph=8.0, value=0.0, unit=None, baseCatalyzed=True, acidCatalyzed=False, phosphorusEster=False, isomer=None)]

In [21]:
# print all the keys of epi_result
print(epi_result[0].__dataclass_fields__.keys())

dict_keys(['parameters', 'chemicalProperties', 'logKow', 'meltingPoint', 'boilingPoint', 'vaporPressure', 'waterSolubilityFromLogKow', 'waterSolubilityFromWaterNt', 'henrysLawConstant', 'logKoa', 'biodegradationRate', 'hydrocarbonBiodegradationRate', 'aerosolAdsorptionFraction', 'atmosphericHalfLife', 'logKoc', 'hydrolysis', 'bioconcentration', 'waterVolatilization', 'sewageTreatmentModel', 'fugacityModel', 'dermalPermeability', 'analogs', 'logKowAnalogs'])

In [32]:
exp_vaporPressure

[{'value': 3890.0, 'units': 'mmHg', 'reference': 'BOUBLIK,T ET AL., 1984'}]

In [20]:
epi_result[0].logKow

LogKowResponse(estimatedValue=logKowEstimatedValue(model=KowModel(logKow=0.3500000014901161, factors=[KowFactor(type='Fragment', description='Formaldehyde experimental value - constant', fragmentCount=1, coefficient=0.12099999934434891, contribution=0.12099999934434891, trainingCount=1, validationCount=0), KowFactor(type='Constant', description='Equation Constant', fragmentCount=0, coefficient=0.0, contribution=0.2290000021457672, trainingCount=0, validationCount=0)], output='-------+-----+--------------------------------------------+---------+--------\n TYPE  | NUM |        LOGKOW FRAGMENT DESCRIPTION         |  COEFF  |  VALUE \n-------+-----+--------------------------------------------+---------+--------\n Frag  |  1  |  Formaldehyde experimental value - constant| 0.1210  |  0.1210\n Const |     |  Equation Constant                         |         |  0.2290\n-------+-----+--------------------------------------------+---------+--------\n                                                         Log Kow   =   0.3500\n', notes='', flags=Flag(isOrganicAcid=False, isAminoAcid=False)), value=0.3500000014901161, units='', valueType='ESTIMATED'), experimentalValues=[ExperimentalValue(author='HANSCH,C ET AL.', year=1995, order=1, value=0.35, units=None, valueType='EXPERIMENTAL')], selectedValue=SelectedValue(value=0.35, units=None, valueType='EXPERIMENTAL'))

In [10]:
[epi_result[0].fugacityModel.model.Sediment[0].HalfLife,
epi_result[0].fugacityModel.model.Soil[0].HalfLife,
epi_result[0].fugacityModel.model.Water[0].HalfLife]

[3240.0, 720.0, 360.0]

In [ ]:
ecosar_result[0]

[ModelResult(qsarClass='Aldehydes (Mono)', organism='Fish', duration='96-hr', endpoint='LC50', concentration=11.226508140563965, maxLogKow=5.0, flags=[]),
 ModelResult(qsarClass='Aldehydes (Mono)', organism='Daphnid', duration='48-hr', endpoint='LC50', concentration=11.985322952270508, maxLogKow=5.0, flags=[]),
 ModelResult(qsarClass='Aldehydes (Mono)', organism='Green Algae', duration='96-hr', endpoint='EC50', concentration=5.865765571594238, maxLogKow=6.400000095367432, flags=[]),
 ModelResult(qsarClass='Aldehydes (Mono)', organism='Fish', duration='', endpoint='ChV', concentration=3.619093179702759, maxLogKow=8.0, flags=[]),
 ModelResult(qsarClass='Aldehydes (Mono)', organism='Daphnid', duration='', endpoint='ChV', concentration=0.09811598062515259, maxLogKow=8.0, flags=[]),
 ModelResult(qsarClass='Aldehydes (Mono)', organism='Green Algae', duration='', endpoint='ChV', concentration=1.7776434421539307, maxLogKow=8.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Fish', duration='96-hr', endpoint='LC50', concentration=748.117431640625, maxLogKow=5.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Daphnid', duration='48-hr', endpoint='LC50', concentration=364.75787353515625, maxLogKow=5.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Green Algae', duration='96-hr', endpoint='EC50', concentration=144.72206115722656, maxLogKow=6.400000095367432, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Fish', duration='', endpoint='ChV', concentration=61.09768295288086, maxLogKow=8.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Daphnid', duration='', endpoint='ChV', concentration=23.279020309448242, maxLogKow=8.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Green Algae', duration='', endpoint='ChV', concentration=26.995397567749023, maxLogKow=8.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Fish (SW)', duration='96-hr', endpoint='LC50', concentration=932.5665283203125, maxLogKow=5.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Mysid', duration='96-hr', endpoint='LC50', concentration=2119.384521484375, maxLogKow=5.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Fish (SW)', duration='', endpoint='ChV', concentration=36.95725631713867, maxLogKow=8.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Mysid (SW)', duration='', endpoint='ChV', concentration=298.7203369140625, maxLogKow=8.0, flags=[]),
 ModelResult(qsarClass='Neutral Organics', organism='Earthworm', duration='14-day', endpoint='LC50', concentration=77.41226196289062, maxLogKow=6.0, flags=[])]

In [5]:
client = EpiSuiteAPIClient()
res = client.submit(cas=ids[1].cas)
res

{'parameters': {'cas': '000100-00-5',
  'smiles': None,
  'caseNumber': None,
  'userLogKow': {'value': -999.0, 'units': '', 'valueType': 'USER_PROVIDED'},
  'userMeltingPoint': {'value': -999.0,
   'units': 'celsius',
   'valueType': 'USER_PROVIDED'},
  'userBoilingPoint': {'value': -999.0,
   'units': 'celsius',
   'valueType': 'USER_PROVIDED'},
  'userWaterSolubility': {'value': -999.0,
   'units': 'mg/L',
   'valueType': 'USER_PROVIDED'},
  'userVaporPressure': {'value': -999.0,
   'units': 'mmHg',
   'valueType': 'USER_PROVIDED'},
  'userHenrysLawConstant': {'value': -999.0,
   'units': 'atm-m3/mol',
   'valueType': 'USER_PROVIDED'},
  'userLogKoa': {'value': -999.0, 'units': '', 'valueType': 'USER_PROVIDED'},
  'userLogKoc': {'value': -999.0,
   'units': 'L/kg',
   'valueType': 'USER_PROVIDED'},
  'userHydroxylReactionRateConstant': {'value': -999.0,
   'units': 'cm3/molecule-sec',
   'valueType': 'USER_PROVIDED'},
  'userDermalPermeabilityCoefficient': {'value': -999.0,
   'units': 'cm/hr',
   'valueType': 'USER_PROVIDED'},
  'userBiodegradationRateRemoveMetals': {'value': True,
   'units': 'boolean',
   'valueType': 'USER_PROVIDED'},
  'userAtmosphericHydroxylRadicalConcentration': {'value': 1500000.0,
   'units': 'radicals/cm3',
   'valueType': 'USER_PROVIDED'},
  'userAtmosphericOzoneConcentration': {'value': 700000000000.0,
   'units': 'molecules/cm3',
   'valueType': 'USER_PROVIDED'},
  'userAtmosphericDaylightHours': {'value': 12.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userStpHalfLifePrimaryClarifier': {'value': 10000.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userStpHalfLifeAerationVessel': {'value': 10000.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userStpHalfLifeSettlingTank': {'value': 10000.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userFugacityHalfLifeAir': {'value': 0.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userFugacityHalfLifeWater': {'value': 0.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userFugacityHalfLifeSoil': {'value': 0.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userFugacityHalfLifeSediment': {'value': 0.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userFugacityEmissionRateAir': {'value': 1000.0,
   'units': 'kg/hour',
   'valueType': 'USER_PROVIDED'},
  'userFugacityEmissionRateWater': {'value': 1000.0,
   'units': 'kg/hour',
   'valueType': 'USER_PROVIDED'},
  'userFugacityEmissionRateSoil': {'value': 1000.0,
   'units': 'kg/hour',
   'valueType': 'USER_PROVIDED'},
  'userFugacityEmissionRateSediment': {'value': 0.0,
   'units': 'kg/hour',
   'valueType': 'USER_PROVIDED'},
  'userFugacityAdvectionTimeAir': {'value': 100.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userFugacityAdvectionTimeWater': {'value': 1000.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userFugacityAdvectionTimeSoil': {'value': 0.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'userFugacityAdvectionTimeSediment': {'value': 50000.0,
   'units': 'hours',
   'valueType': 'USER_PROVIDED'},
  'modules': []},
 'chemicalProperties': {'name': 'P-CHLORONITROBENZENE',
  'systematicName': 'Benzene, 1-chloro-4-nitro-',
  'cas': '000100-00-5',
  'smiles': 'N(=O)(=O)c(ccc(c1)Cl)c1',
  'molecularWeight': 157.55462903638997,
  'molecularFormula': 'C6H4ClNO2',
  'molecularFormulaHtml': 'C<sub>6</sub>H<sub>4</sub>ClNO<sub>2</sub>',
  'organic': True,
  'organicAcid': False,
  'aminoAcid': False,
  'nonStandardMetal': False,
  'flags': None},
 'logKow': {'parameters': {'smiles': 'N(=O)(=O)c(ccc(c1)Cl)c1',
   'cas': '000100-00-5'},
  'estimatedValue': {'model': {'logKow': 2.455199956893921,
    'factors': [{'type': 'Fragment',
      'description': 'Aromatic Carbon',
      'fragmentCount': 6,
      'coefficient': 0.2939999997615814,
      'contribution': 1.7639999389648438,
      'trainingCount': 24,
      'validationCount': 30},
     {'type': 'Fragment',
      'description': '-CL     [chlorine, aromatic attach]',
      'fragmentCount': 1,
      'coefficient': 0.6445000171661377,
      'contribution': 0.6445000171661377,
      'trainingCount': 6,
      'validationCount': 10},
     {'type': 'Fragment',
      'description': '-NO2    [nitro, aromatic attach]',
      'fragmentCount': 1,
      'coefficient': -0.18230000138282776,
      'contribution': -0.18230000138282776,
      'trainingCount': 3,
      'validationCount': 4},
     {'type': 'Constant',
      'description': 'Equation Constant',
      'fragmentCount': 0,
      'coefficient': 0.0,
      'contribution': 0.2290000021457672,
      'trainingCount': 0,
      'validationCount': 0}],
    'output': '-------+-----+--------------------------------------------+---------+--------\n TYPE  | NUM |        LOGKOW FRAGMENT DESCRIPTION         |  COEFF  |  VALUE \n-------+-----+--------------------------------------------+---------+--------\n Frag  |  6  |  Aromatic Carbon                           | 0.2940  |  1.7640\n Frag  |  1  |  -CL     [chlorine, aromatic attach]       | 0.6445  |  0.6445\n Frag  |  1  |  -NO2    [nitro, aromatic attach]          |-0.1823  | -0.1823\n Const |     |  Equation Constant                         |         |  0.2290\n-------+-----+--------------------------------------------+---------+--------\n                                                         Log Kow   =   2.4552\n',
    'notes': '',
    'flags': {'isOrganicAcid': False, 'isAminoAcid': False}},
   'value': 2.455199956893921,
   'units': '',
   'valueType': 'ESTIMATED'},
  'experimentalValues': [{'author': 'HANSCH,C ET AL.',
    'year': 1995,
    'order': 1,
    'value': 2.39,
    'units': None,
    'valueType': 'EXPERIMENTAL'}],
  'selectedValue': {'value': 2.39,
   'units': None,
   'valueType': 'EXPERIMENTAL'}},
 'meltingPoint': {'estimatedValue': {'model': {'factors': [{'type': 'Group',
      'description': '-NO2 (nitro)',
      'fragmentCount': 1,
      'coefficient': 127.23999786376953,
      'totalCoefficient': 127.23999786376953},
     {'type': 'Group',
      'description': 'CH (aromatic)',
      'fragmentCount': 4,
      'coefficient': 8.130000114440918,
      'totalCoefficient': 32.52000045776367},
     {'type': 'Group',
      'description': '-C (aromatic)',
      'fragmentCount': 2,
      'coefficient': 37.02000045776367,
      'totalCoefficient': 74.04000091552734},
     {'type': 'Group',
      'description': '-Cl (to aromat)',
      'fragmentCount': 1,
      'coefficient': 13.550000190734863,
      'totalCoefficient': 13.550000190734863},
     {'type': '*',
      'description': 'Equation Constant',
      'fragmentCount': 0,
      'coefficient': 122.5,
      'totalCoefficient': 122.5}],
    'meltingPointKelvins': 369.8499755859375,
    'meltingPointLimitKelvins': 369.8499755859375,
    'meltingPointCelsius': 96.68997192382812,
    'meltingPointAdaptedJoback': 96.68997192382812,
    'meltingPointGoldOgle': 24.794708251953125,
    'meltingPointMean': 60.742340087890625,
    'meltingPointSelected': 48.759796142578125},
   'value': 48.759796142578125,
   'units': 'celsius',
   'valueType': 'ESTIMATED'},
  'experimentalValues': [{'author': 'Benzenes slope analogy',
    'year': 0,
    'order': 1,
    'value': 83.5,
    'units': 'celsius',
    'valueType': 'EXPERIMENTAL'}],
  'selectedValue': {'value': 83.5,
   'units': 'celsius',
   'valueType': 'EXPERIMENTAL'}},
 'boilingPoint': {'estimatedValue': {'model': {'factors': [{'type': 'Group',
      'description': '-NO2 (nitro)',
      'fragmentCount': 1,
      'coefficient': 113.98999786376953,
      'totalCoefficient': 113.98999786376953},
     {'type': 'Group',
      'description': 'CH (aromatic)',
      'fragmentCount': 4,
      'coefficient': 28.530000686645508,
      'totalCoefficient': 114.12000274658203},
     {'type': 'Group',
      'description': '-C (aromatic)',
      'fragmentCount': 2,
      'coefficient': 30.760000228881836,
      'totalCoefficient': 61.52000045776367},
     {'type': 'Group',
      'description': '-Cl (to aromat)',
      'fragmentCount': 1,
      'coefficient': 36.790000915527344,
      'totalCoefficient': 36.790000915527344},
     {'type': '*',
      'description': 'Equation Constant',
      'fragmentCount': 0,
      'coefficient': 0.0,
      'totalCoefficient': 198.17999267578125}],
    'boilingPointKelvinsUncorrected': 524.5999755859375,
    'boilingPointKelvinsCorrected': 510.2838134765625,
    'boilingPointCelsius': 237.12380981445312},
   'value': 237.12380981445312,
   'units': 'celsius',
   'valueType': 'ESTIMATED'},
  'experimentalValues': [{'author': None,
    'year': 0,
    'order': 1,
    'value': 242.0,
    'units': 'celsius',
    'valueType': 'EXPERIMENTAL'}],
  'selectedValue': {'value': 242.0,
   'units': 'celsius',
   'valueType': 'EXPERIMENTAL'}},
 'vaporPressure': {'estimatedValue': {'model': [{'type': 'Antoine',
     'mmHg': 0.011922466568648815,
     'pa': 1.5895270878653973},
    {'type': 'Grain', 'mmHg': 0.011046068291388286, 'pa': 1.4726839167444692},
    {'type': 'Mackay', 'mmHg': 0.018415611638825435, 'pa': 2.455206174911485},
    {'type': 'Selected',
     'mmHg': 0.011046068291388286,
     'pa': 1.4726839167444692},
    {'type': 'SubCooled',
     'mmHg': 0.04006780683994293,
     'pa': 5.341920143514872}],
   'value': 0.011046068291388286,
   'units': 'mmHg',
   'valueType': 'ESTIMATED'},
  'experimentalValues': [{'author': 'DAUBERT,TE & DANNER,RP',
    'year': 1989,
    'order': 1,
    'value': 0.0219,
    'units': 'mmHg',
    'valueType': 'EXPERIMENTAL'}],
  'selectedValue': {'value': 0.0219,
   'units': 'mmHg',
   'valueType': 'EXPERIMENTAL'}},
 'waterSolubilityFromLogKow': {'parameters': {'smiles': 'N(=O)(=O)c(ccc(c1)Cl)c1',
   'cas': '000100-00-5',
   'logKow': {'value': 2.39, 'units': None, 'valueType': 'EXPERIMENTAL'},
   'meltingPoint': {'value': 83.5,
    'units': 'celsius',
    'valueType': 'EXPERIMENTAL'}},
  'estimatedValue': {'model': {'waterSolubility': 114.31641387939453,
    'factors': [{'type': 'Nitro (-NO2)',
      'description': None,
      'fragmentCount': 1,
      'coefficient': -0.5049999952316284,
      'totalCoefficient': -0.5049999952316284,
      'trainingCount': 75,
      'maxFragmentCount': 1}],
    'equation': 'Log S (mol/L) = 0.693-0.96 log Kow-0.0092(Tm-25)-0.00314 MW + Correction\n Melting Pt (Tm) = 83.5 deg C (Use Tm = 25 for all liquids)\nUser Entered Melting Point: 83.5',
    'notes': '',
    'output': 'MOL FOR: C6 H4 Cl1 N1 O2 \nMOL WT : 157.56\nLog Kow (experimental):  2.39\nLog Kow used by Water solubility estimates:  2.39 (user entered)\n\nEquation Used to Make Water Sol estimate:\n   Log S (mol/L) = 0.693-0.96 log Kow-0.0092(Tm-25)-0.00314 MW + Correction\n\n      Melting Pt (Tm) = 83.50 deg C (Use Tm = 25 for all liquids)\n\n      Correction(s):         Value\n      --------------------   -----\n       Nitro (-NO2)         -0.505\n\n   Log Water Solubility  (in moles/L) :  -3.139\n   Water Solubility at 25 deg C (mg/L):  114.3\n'},
   'value': 114.31641387939453,
   'units': 'mg/L',
   'valueType': 'ESTIMATED'},
  'experimentalValues': [],
  'selectedValue': {'value': 114.31641387939453,
   'units': 'mg/L',
   'valueType': 'ESTIMATED'}},
 'waterSolubilityFromWaterNt': {'parameters': {'smiles': 'N(=O)(=O)c(ccc(c1)Cl)c1',
   'cas': '000100-00-5'},
  'estimatedValue': {'model': {'waterSolubility': 220.7898406982422,
    'factors': [{'type': 'Fragment',
      'description': 'Aromatic Carbon  (C-H type)',
      'fragmentCount': 4,
      'coefficient': -0.3358639180660248,
      'totalCoefficient': -1.3434556722640991,
      'trainingCount': 700,
      'maxFragmentCount': 15},
     {'type': 'Fragment',
      'description': '-CL     [chlorine, aromatic attach]',
      'fragmentCount': 1,
      'coefficient': -0.48780557513237,
      'totalCoefficient': -0.48780557513237,
      'trainingCount': 202,
      'maxFragmentCount': 10},
     {'type': 'Fragment',
      'description': '-NO2    [nitro, aromatic attach]',
      'fragmentCount': 1,
      'coefficient': -0.19150857627391815,
      'totalCoefficient': -0.19150857627391815,
      'trainingCount': 65,
      'maxFragmentCount': 3},
     {'type': 'Fragment',
      'description': 'Aromatic Carbon  (C-substituent type)',
      'fragmentCount': 2,
      'coefficient': -0.5399536490440369,
      'totalCoefficient': -1.0799072980880737,
      'trainingCount': 718,
      'maxFragmentCount': 12},
     {'type': 'Constant',
      'description': 'Equation Constant',
      'fragmentCount': 1,
      'coefficient': 0.24921822547912598,
      'totalCoefficient': 0.24921822547912598,
      'trainingCount': 0,
      'maxFragmentCount': 0}],
    'equation': '',
    'notes': '',
    'output': 'MOL FOR: C6 H4 CL1 N1 O2 \nMOL WT : 157.56\n-------+-----+--------------------------------------------+----------+---------\n TYPE  | NUM |    WATER SOLUBILITY FRAGMENT DESCRIPTION   |  COEFF   |  VALUE  \n-------+-----+--------------------------------------------+----------+---------\n Frag  |  4  |  Aromatic Carbon  (C-H type)               |-0.3359   | -1.3435\n Frag  |  1  |  -CL     [chlorine, aromatic attach]       |-0.4878   | -0.4878\n Frag  |  1  |  -NO2    [nitro, aromatic attach]          |-0.1915   | -0.1915\n Frag  |  2  |  Aromatic Carbon  (C-substituent type)     |-0.5400   | -1.0799\n Const |     |  Equation Constant                         |          |  0.2492\n-------+-----+--------------------------------------------+----------+---------\n                              Log Water Sol (moles/L) at 25 dec C  =   -2.8535\n                              Water Solubility (mg/L) at 25 dec C  =   220.79\n'},
   'value': 220.7898406982422,
   'units': 'mg/L',
   'valueType': 'ESTIMATED'},
  'experimentalValues': [],
  'selectedValue': {'value': 220.7898406982422,
   'units': 'mg/L',
   'valueType': 'ESTIMATED'}},
 'henrysLawConstant': {'parameters': {'smiles': 'N(=O)(=O)c(ccc(c1)Cl)c1',
   'cas': '000100-00-5',
   'waterSolubility': {'value': 114.31641387939453,
    'units': 'mg/L',
    'valueType': 'ESTIMATED'},
   'vaporPressure': {'value': 0.0219,
    'units': 'mmHg',
    'valueType': 'EXPERIMENTAL'},
   'molecularWeight': {'value': 157.55462903638997,
    'units': 'g/mol',
    'valueType': 'NONE'}},
  'estimatedValue': {'model': [{'name': 'VP/WSOL',
     'value': 3.9721220046938924e-05,
     'factors': None,
     'hlcAtm': 3.9721220046938924e-05,
     'hlcUnitless': 0.001623566916729347,
     'hlcPaMol': 4.02475262125609,
     'notes': ''},
    {'name': 'Bond',
     'value': 3.191138744354248,
     'factors': [{'type': 'Hydrogen',
       'description': 'Hydrogen to Carbon (aromatic) Bonds',
       'fragmentCount': 4,
       'totalCoefficient': -0.6171759963035583,
       'trainingCount': 93,
       'maxFragmentCount': 12},
      {'type': 'Fragment',
       'description': 'Car-Car',
       'fragmentCount': 6,
       'totalCoefficient': 1.5828419923782349,
       'trainingCount': 94,
       'maxFragmentCount': 21},
      {'type': 'Fragment',
       'description': 'Car-CL',
       'fragmentCount': 1,
       'totalCoefficient': -0.024102000519633293,
       'trainingCount': 11,
       'maxFragmentCount': 6},
      {'type': 'Fragment',
       'description': 'Car-NO2',
       'fragmentCount': 1,
       'totalCoefficient': 2.249574899673462,
       'trainingCount': 9,
       'maxFragmentCount': 2}],
     'hlcAtm': 1.5751347746117972e-05,
     'hlcUnitless': 0.0006439635180868208,
     'hlcPaMol': 1.5960053205490112,
     'notes': ''},
    {'name': 'Group',
     'value': 2.809999942779541,
     'factors': [{'type': 'NONE    ',
       'description': 'Car-H (Car)(Car)',
       'fragmentCount': 4,
       'totalCoefficient': 0.4399999976158142,
       'trainingCount': 0,
       'maxFragmentCount': 0},
      {'type': 'NONE    ',
       'description': 'Car (Car)(Car)(CL)',
       'fragmentCount': 1,
       'totalCoefficient': 0.18000000715255737,
       'trainingCount': 0,
       'maxFragmentCount': 0},
      {'type': 'NONE    ',
       'description': 'Car (Car)(Car)(NO2)',
       'fragmentCount': 1,
       'totalCoefficient': 2.190000057220459,
       'trainingCount': 0,
       'maxFragmentCount': 0}],
     'hlcAtm': 3.788405956584029e-05,
     'hlcUnitless': 0.00154881679918617,
     'hlcPaMol': 3.838602304458618,
     'notes': ''}],
   'value': 3.788405956584029e-05,
   'units': 'atm-m3/mol',
   'valueType': 'ESTIMATED'},
  'experimentalValues': [{'author': 'ALTSCHUH,J ET AL.',
    'year': 1999,
    'order': 1,
    'value': 4.89e-06,
    'units': 'atm-m3/mol',
    'valueType': 'EXPERIMENTAL'}],
  'selectedValue': {'value': 4.89e-06,
   'units': 'atm-m3/mol',
   'valueType': 'EXPERIMENTAL'}},
 'logKoa': {'parameters': {'smiles': 'N(=O)(=O)c(ccc(c1)Cl)c1',
   'cas': '000100-00-5',
   'logKow': {'value': 2.39, 'units': None, 'valueType': 'EXPERIMENTAL'},
   'henrysLawConstant': {'value': 4.89e-06,
    'units': 'atm-m3/mol',
    'valueType': 'EXPERIMENTAL'}},
  'estimatedValue': {'model': {'kow': 245.4708915685031,
    'kaw': 0.0001998740777202864,
    'koa': 1228127.7010419886,
    'logKoa': 6.089243527207758},
   'value': 6.089243527207758,
   'units': '',
   'valueType': 'ESTIMATED'},
  'experimentalValues': [],
  'selectedValue': {'value': 6.089243527207758,
   'units': '',
   'valueType': 'ESTIMATED'}},
 'biodegradationRate': {'parameters': {'smiles': 'N(=O)(=O)c(ccc(c1)Cl)c1',
   'cas': '000100-00-5',
   'removeMetals': True},
  'models': [{'name': 'Linear Model Prediction',
    'value': 0.18507696688175201,
    'factors': [{'type': 'Fragment',
      'description': 'Aromatic chloride   [-CL]',
      'fragmentCount': 1,
      'coefficient': -0.18242000043392181,
      'totalCoefficient': -0.18242000043392181,
      'trainingCount': 40,
      'maxFragmentCount': 6},
     {'type': 'Fragment',
      'description': 'Aromatic nitro  [-NO2]',
      'fragmentCount': 1,
      'coefficient': -0.30504000186920166,
      'totalCoefficient': -0.30504000186920166,
      'trainingCount': 14,
      'maxFragmentCount': 2},
     {'type': 'Molecular Weight',
      'description': 'Molecular Weight Parameter',
      'fragmentCount': 0,
      'coefficient': 0.0,
      'totalCoefficient': -0.07500886917114258,
      'trainingCount': 0,
      'maxFragmentCount': 0},
     {'type': 'Constant',
      'description': 'Equation Constant',
      'fragmentCount': 0,
      'coefficient': 0.0,
      'totalCoefficient': 0.7475458383560181,
      'trainingCount': 0,
      'maxFragmentCount': 0}]},
   {'name': 'Non-Linear Model Prediction',
    'value': 0.022916589282545027,
    'factors': [{'type': 'Fragment',
      'description': 'Aromatic chloride   [-CL]',
      'fragmentCount': 1,
      'coefficient': -2.015500068664551,
      'totalCoefficient': -2.015500068664551,
      'trainingCount': 40,
      'maxFragmentCount': 6},
     {'type': 'Fragment',
      'description': 'Aromatic nitro  [-NO2]',
      'fragmentCount': 1,
      'coefficient': -2.5085999965667725,
      'totalCoefficient': -2.5085999965667725,
      'trainingCount': 14,
      'maxFragmentCount': 2},
     {'type': 'Molecular Weight',
      'description': 'Molecular Weight Parameter',
      'fragmentCount': 0,
      'coefficient': 0.0,
      'totalCoefficient': -2.2373108863830566,
      'trainingCount': 0,
      'maxFragmentCount': 0}]},
   {'name': 'Ultimate Biodegradation Timeframe',
    'value': 2.474800005555153,
    'factors': [{'type': 'Fragment',
      'description': 'Aromatic chloride   [-CL]',
      'fragmentCount': 1,
      'coefficient': -0.20659999549388885,
      'totalCoefficient': -0.20659999549388885,
      'trainingCount': 27,
      'maxFragmentCount': 6},
     {'type': 'Fragment',
      'description': 'Aromatic nitro  [-NO2]',
      'fragmentCount': 1,
      'coefficient': -0.16958999633789062,
      'totalCoefficient': -0.16958999633789062,
      'trainingCount': 13,
      'maxFragmentCount': 2},
     {'type': 'Molecular Weight',
      'description': 'Molecular Weight Parameter',

## EPI Suite experimental data
TODO: explain where the data comes from

In [36]:
h = HenryData()
s = SolubilityData()
h.HLC("50-00-0"), s.solubility("50-00-0")

({'CASRN': '50-00-0',
  'name': 'FORMALDEHYDE',
  'value': 3.37e-07,
  'unit': 'atm-m3/mole',
  'Temp (C)': 25.0,
  'type': 'EXP'},
 {'CASRN': '50-00-0',
  'name': 'FORMALDEHYDE',
  'class': 'Aldehydes',
  'logKow': 0.35,
  'water_solubility_mg_per_L': 400000.0,
  'log_mol_per_L': 1.121})

In [24]:
h.data

,CAS Number,Name,WSol (mg/L),WS Temp,WS type,Wsol Reference,VP (mm Hg),VP Temp,VP type,VP Reference,HenryLC (atm-m3/mole),HLC Temp,HLC type,HenryLC Reference
0,50-00-0,FORMALDEHYDE,400000.00000,20.0,EXP,"PICKRELL,JA ET AL. (1983)",3.890000e+03,25.0,EXT,"BOUBLIK,T ET AL. (1984)",3.370000e-07,25.0,EXP,"BETTERTON,EA & HOFFMAN,MR (1988)"
1,50-21-5,LACTIC ACID,1000000.00000,NaN,EXP,MERCK INDEX (2001),8.130000e-02,25.0,EXP,"DAUBERT,TE & DANNER,RP (1989)",8.130000e-08,25.0,EST,VP/WSOL
2,50-29-3,"P,P'-DDT",0.00550,25.0,EXP,"YALKOWSKY,SH & DANNENFELSER,RM (1992)",1.600000e-07,20.0,EXP,"BIDLEMAN,TF & FOREMAN,WT (1987)",8.320000e-06,25.0,EXP,"ALTSCHUH,J ET AL. (1999)"
3,50-31-7,"2,3,6-TRICHLOROBENZOIC ACID",7700.00000,22.0,EXP,"MARTIN,H & WORTHING,CR (1977)",5.500000e-04,25.0,EXP,"FREAR,DS (1976)",2.120000e-08,25.0,EST,VP/WSOL
4,50-32-8,BENZO(A)PYRENE,0.00162,25.0,EXP,"MAY,WE ET AL. (1983)",5.490000e-09,25.0,EXT,"MURRAY,JJ ET AL. (1974)",4.570000e-07,25.0,EXP,"TEN HULSCHER,TEM ET AL. (1992)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824,SRC003-82-1,4-Nitrooxy-2-butanol,22500.00000,25.0,EST,"MEYLAN,WM ET AL. (1996)",1.010000e-01,25.0,EST,"NEELY,WB & BLAU,GE (1985)",7.350000e-08,18.0,EXP,"TREVES,K ET AL. (2000)"
1825,SRC003-82-2,3-Nitrooxy-1-propanol,58100.00000,25.0,EST,"MEYLAN,WM ET AL. (1996)",1.100000e-01,25.0,EST,"NEELY,WB & BLAU,GE (1985)",7.140000e-08,18.0,EXP,"TREVES,K ET AL. (2000)"
1826,SRC003-82-3,4-Nitrooxy-1-butanol,19500.00000,25.0,EST,"MEYLAN,WM ET AL. (1996)",3.330000e-02,25.0,EST,"NEELY,WB & BLAU,GE (1985)",3.450000e-08,18.0,EXP,"TREVES,K ET AL. (2000)"
1827,SRC003-82-4,5-Nitrooxy-2-pentanol,7480.00000,25.0,EST,"MEYLAN,WM ET AL. (1996)",3.050000e-02,25.0,EST,"NEELY,WB & BLAU,GE (1985)",2.720000e-08,18.0,EXP,"TREVES,K ET AL. (2000)"
1828,SRC003-82-5,4-Nitrooxy-1-pentanol,7480.00000,25.0,EST,"MEYLAN,WM ET AL. (1996)",2.080000e-02,25.0,EST,"NEELY,WB & BLAU,GE (1985)",4.880000e-08,18.0,EXP,"TREVES,K ET AL. (2000)"

## Converting Results to DataFrames
The new DataFrame utilities allow easy conversion of EPI Suite and EcoSAR results to pandas DataFrames for analysis.

In [51]:
from pyepisuite.dataframe_utils import (
    episuite_to_dataframe,
    episuite_experimental_to_dataframe,
    ecosar_to_dataframe,
    combine_episuite_ecosar_dataframes,
    export_to_excel,
    create_summary_statistics
)

In [53]:
# Convert EPI Suite results to DataFrame
epi_df = episuite_to_dataframe(epi_result)
print("EPI Suite DataFrame shape:", epi_df.shape)
print("\nColumns:", list(epi_df.columns))
epi_df.head()

EPI Suite DataFrame shape: (4, 45)

Columns: ['cas', 'name', 'systematic_name', 'smiles', 'molecular_weight', 'molecular_formula', 'is_organic', 'is_organic_acid', 'is_amino_acid', 'is_non_standard_metal', 'log_kow_estimated', 'log_kow_units', 'melting_point_estimated', 'melting_point_units', 'boiling_point_estimated', 'boiling_point_units', 'vapor_pressure_estimated', 'vapor_pressure_units', 'water_solubility_logkow_estimated', 'water_solubility_logkow_units', 'water_solubility_waternt_estimated', 'water_solubility_waternt_units', 'henrys_law_constant_estimated', 'henrys_law_constant_units', 'log_koa_estimated', 'log_koa_units', 'log_koc_estimated', 'log_koc_units', 'atmospheric_half_life_estimated', 'atmospheric_half_life_units', 'aerosol_adsorption_fraction_estimated', 'aerosol_adsorption_fraction_units', 'hydrocarbon_biodegradation_rate_estimated', 'hydrocarbon_biodegradation_rate_units', 'bioconcentration_factor', 'log_bioconcentration_factor', 'bioaccumulation_factor', 'log_bioaccumulation_factor', 'biotransformation_half_life', 'river_half_life_hours', 'lake_half_life_hours', 'dermal_permeability_coefficient', 'dermal_absorbed_dose', 'lag_time_hours', 'fugacity_persistence']

,cas,name,systematic_name,smiles,molecular_weight,molecular_formula,is_organic,is_organic_acid,is_amino_acid,is_non_standard_metal,...,log_bioconcentration_factor,bioaccumulation_factor,log_bioaccumulation_factor,biotransformation_half_life,river_half_life_hours,lake_half_life_hours,dermal_permeability_coefficient,dermal_absorbed_dose,lag_time_hours,fugacity_persistence
0,000050-00-0,FORMALDEHYDE,Formaldehyde,C=O,30.026022,CH2O,True,False,False,False,...,0.50,1.06,0.02,0.00,952.824482,1.044040e+04,0.001816,9.416935e+06,0.156825,393.759869
1,000100-00-5,P-CHLORONITROBENZENE,"Benzene, 1-chloro-4-nitro-",C1=C(C=CC(=C1)N(=O)=O)Cl,157.554629,C6H4ClNO2,True,False,False,False,...,1.24,21.67,1.34,-0.48,151.611013,1.759201e+03,0.007927,1.819665e+05,0.814874,1068.953616
2,000100-02-7,4-NITROPHENOL,"Phenol, 4-nitro-",C1=C(C=CC(=C1)O)N(=O)=O,139.109037,C6H5NO3,True,False,False,False,...,0.93,6.13,0.79,0.00,117723.837918,1.284359e+06,0.004826,1.342030e+07,0.642063,751.433416
3,000111-65-9,OCTANE,Octane,CCCCCCCC,114.228821,C8H18,True,False,False,False,...,3.08,1155.12,3.06,0.00,1.090945,1.015296e+02,0.991844,9.935426e+04,0.465547,75.035095

In [55]:
# Show the expanded DataFrame with all the new properties
print("All available columns in the expanded EPI Suite DataFrame:")
print(f"Total columns: {len(epi_df.columns)}")
print()

# Categorize the columns for better understanding
chemical_id_cols = [col for col in epi_df.columns if any(keyword in col for keyword in ['cas', 'name', 'smiles', 'molecular', 'is_'])]
physical_props_cols = [col for col in epi_df.columns if any(keyword in col for keyword in ['log_kow', 'melting', 'boiling', 'vapor', 'water_solubility', 'henrys', 'log_koa', 'log_koc'])]
environmental_cols = [col for col in epi_df.columns if any(keyword in col for keyword in ['atmospheric', 'aerosol', 'biodeg', 'hydroxyl', 'ozone'])]
bioconcentration_cols = [col for col in epi_df.columns if 'bioconcentration' in col or 'bioaccumulation' in col or 'biotransformation' in col or 'trophic' in col]
fate_cols = [col for col in epi_df.columns if any(keyword in col for keyword in ['fugacity', 'sewage', 'dermal', 'river', 'lake', 'hydrolysis'])]

print("Chemical Identification:")
for col in chemical_id_cols:
    print(f"  - {col}")

print(f"\nPhysical & Chemical Properties ({len(physical_props_cols)} columns):")
for col in physical_props_cols[:8]:  # Show first 8
    print(f"  - {col}")
if len(physical_props_cols) > 8:
    print(f"  ... and {len(physical_props_cols) - 8} more")

print(f"\nEnvironmental Fate ({len(environmental_cols)} columns):")
for col in environmental_cols:
    print(f"  - {col}")

print(f"\nBioconcentration & Bioaccumulation ({len(bioconcentration_cols)} columns):")
for col in bioconcentration_cols:
    print(f"  - {col}")

print(f"\nFate & Transport ({len(fate_cols)} columns):")
for col in fate_cols[:8]:  # Show first 8
    print(f"  - {col}")
if len(fate_cols) > 8:
    print(f"  ... and {len(fate_cols) - 8} more")

# Show available chemicals and sample values for the first one
print(f"\nAvailable chemicals in DataFrame:")
for idx, row in epi_df.iterrows():
    print(f"  {row['name']} (CAS: {row['cas']})")

print(f"\nSample values for {epi_df.iloc[0]['name']} (CAS: {epi_df.iloc[0]['cas']}):")
first_chemical = epi_df.iloc[0]
key_properties = ['log_kow_estimated', 'atmospheric_half_life_estimated', 'bioconcentration_factor', 'fugacity_persistence']
for prop in key_properties:
    if prop in first_chemical:
        print(f"  {prop}: {first_chemical[prop]}")
    else:
        print(f"  {prop}: Not available")

All available columns in the expanded EPI Suite DataFrame:
Total columns: 45

Chemical Identification:
  - cas
  - name
  - systematic_name
  - smiles
  - molecular_weight
  - molecular_formula
  - is_organic
  - is_organic_acid
  - is_amino_acid
  - is_non_standard_metal

Physical & Chemical Properties (18 columns):
  - log_kow_estimated
  - log_kow_units
  - melting_point_estimated
  - melting_point_units
  - boiling_point_estimated
  - boiling_point_units
  - vapor_pressure_estimated
  - vapor_pressure_units
  ... and 10 more

Environmental Fate (6 columns):
  - atmospheric_half_life_estimated
  - atmospheric_half_life_units
  - aerosol_adsorption_fraction_estimated
  - aerosol_adsorption_fraction_units
  - hydrocarbon_biodegradation_rate_estimated
  - hydrocarbon_biodegradation_rate_units

Bioconcentration & Bioaccumulation (5 columns):
  - bioconcentration_factor
  - log_bioconcentration_factor
  - bioaccumulation_factor
  - log_bioaccumulation_factor
  - biotransformation_half_life

Fate & Transport (5 columns):
  - river_half_life_hours
  - lake_half_life_hours
  - dermal_permeability_coefficient
  - dermal_absorbed_dose
  - fugacity_persistence

Available chemicals in DataFrame:
  FORMALDEHYDE (CAS: 000050-00-0)
  P-CHLORONITROBENZENE (CAS: 000100-00-5)
  4-NITROPHENOL (CAS: 000100-02-7)
  OCTANE (CAS: 000111-65-9)

Sample values for FORMALDEHYDE (CAS: 000050-00-0):
  log_kow_estimated: 0.3500000014901161
  atmospheric_half_life_estimated: 15.787435531616211
  bioconcentration_factor: 3.16
  fugacity_persistence: 393.75986900846414

In [57]:
# Compare DataFrame approach vs. direct object access
# The DataFrame provides a clean, tabular view of all the properties that were previously
# accessed individually through the complex object hierarchy

print("=== Comparison: Direct Object Access vs DataFrame Access ===")
print()

# Use the first chemical in our results
first_chemical_cas = epi_df.iloc[0]['cas']
first_chemical_name = epi_df.iloc[0]['name']

# Original way: Direct object access (as shown in previous cells)
print("1. Direct Object Access (original approach):")
cas_direct = epi_result[0].chemicalProperties.cas
name_direct = epi_result[0].chemicalProperties.name
log_kow_direct = epi_result[0].logKow.estimatedValue.value
bioconc_factor_direct = epi_result[0].bioconcentration.bioconcentrationFactor

print(f"   CAS: {cas_direct}")
print(f"   Name: {name_direct}")
print(f"   Log Kow: {log_kow_direct}")
print(f"   BCF: {bioconc_factor_direct}")
print()

# New way: DataFrame access
print("2. DataFrame Access (new approach):")
first_row = epi_df.iloc[0]
print(f"   CAS: {first_row['cas']}")
print(f"   Name: {first_row['name']}")
print(f"   Log Kow: {first_row['log_kow_estimated']}")
print(f"   BCF: {first_row['bioconcentration_factor']}")
print()

print("3. Advantages of DataFrame approach:")
print("   ✓ All chemicals in one table for easy comparison")
print("   ✓ Built-in pandas functionality (filtering, sorting, grouping)")
print("   ✓ Easy export to Excel/CSV")
print("   ✓ Statistical analysis with describe(), mean(), etc.")
print("   ✓ Visualization with matplotlib/plotly")
print("   ✓ No need to navigate complex object hierarchies")
print()

# Show some pandas functionality
print("4. Example pandas operations:")
print(f"   Mean Log Kow across all chemicals: {epi_df['log_kow_estimated'].mean():.2f}")
print(f"   Chemicals with BCF > 10: {len(epi_df[epi_df['bioconcentration_factor'] > 10])}")
print(f"   Range of atmospheric half-lives: {epi_df['atmospheric_half_life_estimated'].min():.1f} - {epi_df['atmospheric_half_life_estimated'].max():.1f} hours")
print()

# Show all the new properties that are now easily accessible
print("5. New properties easily accessible in DataFrame (sample from first chemical):")
new_properties = [
    'aerosol_adsorption_fraction_estimated',
    'hydrocarbon_biodegradation_rate_estimated', 
    'river_half_life_hours',
    'lake_half_life_hours',
    'dermal_permeability_coefficient',
    'fugacity_persistence'
]

for prop in new_properties:
    if prop in first_row and first_row[prop] is not None:
        print(f"   {prop}: {first_row[prop]}")
    else:
        print(f"   {prop}: Not available")

=== Comparison: Direct Object Access vs DataFrame Access ===

1. Direct Object Access (original approach):
   CAS: 000050-00-0
   Name: FORMALDEHYDE
   Log Kow: 0.3500000014901161
   BCF: 3.16

2. DataFrame Access (new approach):
   CAS: 000050-00-0
   Name: FORMALDEHYDE
   Log Kow: 0.3500000014901161
   BCF: 3.16

3. Advantages of DataFrame approach:
   ✓ All chemicals in one table for easy comparison
   ✓ Built-in pandas functionality (filtering, sorting, grouping)
   ✓ Easy export to Excel/CSV
   ✓ Statistical analysis with describe(), mean(), etc.
   ✓ Visualization with matplotlib/plotly
   ✓ No need to navigate complex object hierarchies

4. Example pandas operations:
   Mean Log Kow across all chemicals: 2.25
   Chemicals with BCF > 10: 2
   Range of atmospheric half-lives: 15.5 - 748.7 hours

5. New properties easily accessible in DataFrame (sample from first chemical):
   aerosol_adsorption_fraction_estimated: 5.377725238587039e-10
   hydrocarbon_biodegradation_rate_estimated: nan
   river_half_life_hours: 952.8244821446641
   lake_half_life_hours: 10440.401136398748
   dermal_permeability_coefficient: 0.0018156810226975285
   fugacity_persistence: 393.75986900846414

In [24]:
# Convert EcoSAR results to DataFrame
ecosar_df = ecosar_to_dataframe(ecosar_result)
print("EcoSAR DataFrame shape:", ecosar_df.shape)
print("\nColumns:", list(ecosar_df.columns))
ecosar_df.head()

EcoSAR DataFrame shape: (60, 12)

Columns: ['cas', 'smiles', 'log_kow_input', 'water_solubility_input', 'melting_point_input', 'qsar_class', 'organism', 'duration', 'endpoint', 'concentration', 'max_log_kow', 'flags']

,cas,smiles,log_kow_input,water_solubility_input,melting_point_input,qsar_class,organism,duration,endpoint,concentration,max_log_kow,flags
0,000050-00-0,C=O,0.35,54982.121094,-92.0,Aldehydes (Mono),Fish,96-hr,LC50,11.226508,5.0,None
1,000050-00-0,C=O,0.35,54982.121094,-92.0,Aldehydes (Mono),Daphnid,48-hr,LC50,11.985323,5.0,None
2,000050-00-0,C=O,0.35,54982.121094,-92.0,Aldehydes (Mono),Green Algae,96-hr,EC50,5.865766,6.4,None
3,000050-00-0,C=O,0.35,54982.121094,-92.0,Aldehydes (Mono),Fish,,ChV,3.619093,8.0,None
4,000050-00-0,C=O,0.35,54982.121094,-92.0,Aldehydes (Mono),Daphnid,,ChV,0.098116,8.0,None

In [25]:
# Combine EPI Suite and EcoSAR DataFrames
combined_df = combine_episuite_ecosar_dataframes(epi_df, ecosar_df)
print("Combined DataFrame shape:", combined_df.shape)
combined_df.head()

Combined DataFrame shape: (4, 48)

,cas,name,systematic_name,smiles,molecular_weight,molecular_formula,log_kow_estimated,log_kow_units,melting_point_estimated,melting_point_units,...,dermal_absorbed_dose,lag_time_hours,fugacity_persistence,qsar_class_<lambda>,organism_<lambda>,endpoint_<lambda>,concentration_min,concentration_max,concentration_mean,flags_<lambda>
0,000050-00-0,FORMALDEHYDE,Formaldehyde,C=O,30.026022,CH2O,0.3500,,-110.936310,celsius,...,9.416935e+06,0.156825,393.759869,"Aldehydes (Mono), Neutral Organics","Fish, Daphnid, Green Algae, Fish (SW), Mysid, ...","LC50, EC50, ChV",0.098,2119.385,286.387,
1,000100-00-5,P-CHLORONITROBENZENE,"Benzene, 1-chloro-4-nitro-",C1=C(C=CC(=C1)N(=O)=O)Cl,157.554629,C6H4ClNO2,2.4552,,55.864185,celsius,...,1.819665e+05,0.814874,1068.953616,Neutral Organics,"Fish, Daphnid, Green Algae, Fish (SW), Mysid, ...","LC50, EC50, ChV",3.204,249.571,46.948,Chemical may not be soluble enough to measure ...
2,000100-02-7,4-NITROPHENOL,"Phenol, 4-nitro-",C1=C(C=CC(=C1)O)N(=O)=O,139.109037,C6H5NO3,1.9082,,70.760353,celsius,...,1.342030e+07,0.642063,751.433416,"Neutral Organics, Phenols","Fish, Daphnid, Green Algae, Fish (SW), Mysid, ...","LC50, EC50, ChV",0.980,247.113,49.838,
3,000111-65-9,OCTANE,Octane,CCCCCCCC,114.228821,C8H18,4.2702,,-68.453461,celsius,...,9.935426e+04,0.465547,75.035095,Neutral Organics,"Fish, Daphnid, Green Algae, Fish (SW), Mysid, ...","LC50, EC50, ChV",0.000,92.945,8.536,Chemical may not be soluble enough to measure ...

In [26]:
# Extract experimental values
exp_df = episuite_experimental_to_dataframe(epi_result)
print("Experimental values DataFrame shape:", exp_df.shape)
print("\nUnique properties with experimental data:")
print(exp_df['property'].value_counts())
exp_df.head(10)

Experimental values DataFrame shape: (24, 9)

Unique properties with experimental data:
property
log_kow                     4
melting_point               4
boiling_point               4
vapor_pressure              4
henrys_law_constant         2
water_solubility_logkow     2
water_solubility_waternt    2
log_koc                     1
log_koa                     1
Name: count, dtype: int64

,cas,name,property,value,units,author,year,order,value_type
0,000050-00-0,FORMALDEHYDE,log_kow,3.500000e-01,None,"HANSCH,C ET AL.",1995,1,EXPERIMENTAL
1,000050-00-0,FORMALDEHYDE,melting_point,-9.200000e+01,celsius,"ZHOU,X & MOPPER,K",1990,1,EXPERIMENTAL
2,000050-00-0,FORMALDEHYDE,boiling_point,-1.950000e+01,celsius,None,0,1,EXPERIMENTAL
3,000050-00-0,FORMALDEHYDE,vapor_pressure,3.890000e+03,mmHg,"BOUBLIK,T ET AL.",1984,1,EXPERIMENTAL
4,000050-00-0,FORMALDEHYDE,henrys_law_constant,3.370000e-07,atm-m3/mol,"BETTERTON,EA & HOFFMAN,MR",1988,1,EXPERIMENTAL
5,000100-00-5,P-CHLORONITROBENZENE,log_kow,2.390000e+00,None,"HANSCH,C ET AL.",1995,1,EXPERIMENTAL
6,000100-00-5,P-CHLORONITROBENZENE,melting_point,8.350000e+01,celsius,Benzenes slope analogy,0,1,EXPERIMENTAL
7,000100-00-5,P-CHLORONITROBENZENE,boiling_point,2.420000e+02,celsius,None,0,1,EXPERIMENTAL
8,000100-00-5,P-CHLORONITROBENZENE,vapor_pressure,2.190000e-02,mmHg,"DAUBERT,TE & DANNER,RP",1989,1,EXPERIMENTAL
9,000100-00-5,P-CHLORONITROBENZENE,henrys_law_constant,4.890000e-06,atm-m3/mol,"ALTSCHUH,J ET AL.",1999,1,EXPERIMENTAL

In [27]:
# Export to Excel with multiple sheets
export_data = {
    'EPI_Suite_Results': epi_df,
    'EcoSAR_Results': ecosar_df,
    'Experimental_Values': exp_df,
    'Summary_Statistics': create_summary_statistics(epi_df)
}

export_to_excel(export_data, 'pyepisuite_results.xlsx')
print("Data exported to pyepisuite_results.xlsx")

Data exported to pyepisuite_results.xlsx
Data exported to pyepisuite_results.xlsx

## Complete Workflow Example
This example demonstrates the full PyEPISuite workflow from search to analysis:

In [3]:
# Complete PyEPISuite workflow example
import pandas as pd
import numpy as np

# Step 1: Define chemicals of interest
chemical_set = {
    "Pharmaceuticals": ["50-78-2", "58-08-2"],  # Aspirin, Caffeine
    "Solvents": ["67-56-1", "64-17-5"],         # Methanol, Ethanol  
    "Industrial": ["100-41-4", "108-88-3"]      # Ethylbenzene, Toluene
}

# Flatten the list
all_chemicals = [cas for category in chemical_set.values() for cas in category]
print(f"Analyzing {len(all_chemicals)} chemicals from {len(chemical_set)} categories")

# Step 2: Search and submit for predictions
ids = search_episuite_by_cas(all_chemicals)
epi_results, ecosar_results = submit_to_episuite(ids)

# Step 3: Convert to DataFrames
epi_df = episuite_to_dataframe(epi_results)
ecosar_df = ecosar_to_dataframe(ecosar_results)

# Add chemical categories
category_map = {}
for category, cas_list in chemical_set.items():
    for cas in cas_list:
        category_map[cas] = category

epi_df['category'] = epi_df['cas'].map(category_map)

print(f"\\nDataFrame created with {len(epi_df)} chemicals and {len(epi_df.columns)} properties")
print(f"Categories: {epi_df['category'].value_counts().to_dict()}")

# Step 4: Basic analysis
key_properties = ['log_kow_estimated', 'water_solubility_logkow_estimated', 
                 'bioconcentration_factor', 'atmospheric_half_life_estimated']

print("\\nKey Properties Summary:")
summary = epi_df.groupby('category')[key_properties].mean().round(2)
print(summary)

# Step 5: Identify chemicals of potential concern
concern_criteria = (
    (epi_df['log_bioconcentration_factor'] > 3) |  # High bioaccumulation
    (epi_df['atmospheric_half_life_estimated'] > 48)  # Persistent
)

chemicals_of_concern = epi_df[concern_criteria]
if len(chemicals_of_concern) > 0:
    print(f"\\nChemicals of potential environmental concern: {len(chemicals_of_concern)}")
    for _, row in chemicals_of_concern.iterrows():
        print(f"  {row['name']} (CAS: {row['cas']}) - Category: {row['category']}")
else:
    print("\\nNo chemicals meet the concern criteria in this dataset")

print("\\n✅ Complete workflow demonstrated successfully!")

Analyzing 6 chemicals from 3 categories

NameError: name 'search_episuite_by_cas' is not defined

# USEtox format

The USEtox input format is in the path `data/usetox3/AA_Model_substance_data_Default.xlsx` in the sheet `Substance inputs`. We use the numbers obtained from the episuite and add the results to the `Substance inputs` sheet that serves as template.

In [2]:
import pandas as pd
import os

df = pd.read_excel(os.path.join("..", 'data', "usetox3", 'AA_Model_substance_data_Default.xlsx'),
                   sheet_name="Substance inputs", skiprows=1)
df.keys()

Index(['RowNr', 'CAS RN', 'Name', 'PesticideTargetClass', 'PesticideChemClass',
       'MW', 'Molar volume', 'pKaChemClass', 'pKa.gain', 'pKa.loss', 'KOW',
       'Koc', 'KH25C', 'Pvap25', 'Sol25', 'KDOC', 'KpSS', 'KpSd', 'KpSl',
       'T1/2A', 'T1/2W', 'T1/2Sd', 'T1/2Sl', 'T1/2surface', 'T1/2P',
       'T1/2wheat', 'T1/2rice', 'T1/2tomato', 'T1/2apple', 'T1/2lettuce',
       'T1/2potato', 'T1/2WWTP.biodeg', 'E', 'S', 'A', 'B', 'V', 'L',
       'BAFroot', 'BAFleaf', 'BTFmeat', 'BTFmilk', 'BAFfish', 'HC20',
       'HC20soil', 'Data source_inh', 'EC10inh,noncanc',
       'EC10inh,noncanc GSD2', 'RfC', 'Data source_ing', 'ED10ing,noncanc',
       'ED10ing,noncanc GSD2', 'RfDing', 'Data source_derm',
       'ED10derm,noncanc', 'ED10derm,noncanc GSD2', 'RfDderm',
       'Data source_inh.1', 'EC10inh,noncanc.1', 'EC10inh,noncanc GSD2.1',
       'RfC.1', 'Data source_ing.1', 'ED10ing,noncanc.1',
       'ED10ing,noncanc GSD2.1', 'RfDing.1', 'Data source_derm.1',
       'ED10derm,noncanc.1', 'ED10derm,noncanc GSD2.1', 'RfDderm.1',
       'ED50inh,canc', 'ED50ing,canc', 'ED50derm,canc',
       'Flagged "indicative" Characterization factor "F"', 'Unnamed: 73',
       'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77',
       'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81',
       'Unnamed: 82', 'Unnamed: 83', 'USEtox identification number',
       'Data source'],
      dtype='object')

## Using USEtoxInput Class

The new `USEtoxInput` class provides a comprehensive solution for populating USEtox Excel templates with PyEPISuite data.

In [1]:
# Import the USEtoxInput class
from pyepisuite.usetox_input import USEtoxInput, create_usetox_input_from_episuite

# Assume we have episuite_df from previous cells (you'll need to run those first)
# For demo, let's create a sample of the first few chemicals
sample_df = episuite_df.head(3)  # Take first 3 chemicals

print("Sample PyEPISuite data:")
print(sample_df[['cas', 'name', 'molecular_weight', 'log_kow_estimated', 'henrys_law_constant_estimated']].head())

NameError: name 'episuite_df' is not defined

In [ ]:
# Method 1: Step-by-step approach
try:
    # Initialize USEtoxInput with the template
    usetox_input = USEtoxInput()
    
    # Populate with PyEPISuite data
    populated_df = usetox_input.populate_from_episuite_dataframe(sample_df)
    
    print(f"Populated USEtox template with {len(sample_df)} chemicals")
    print("\nFirst few rows of populated data:")
    print(populated_df[['RowNr', 'CAS RN', 'Name', 'MW', 'KOW', 'Koc']].head())
    
    # Get summary statistics
    stats = usetox_input.get_summary_statistics()
    print(f"\nSummary: {stats['total_chemicals']} chemicals populated")
    
    # Validate data
    validation = usetox_input.validate_data()
    if validation['warnings']:
        print("Warnings:", validation['warnings'])
    if validation['errors']:
        print("Errors:", validation['errors'])
    
except Exception as e:
    print(f"Error: {e}")
    print("This might be because the USEtox template file is not found.")
    print("You can provide a custom template path or create a mock template for testing.")

In [ ]:
# Export to Excel file
output_file = "usetox_input_populated.xlsx"

try:
    # Method 2: Using the convenience function (one-liner approach)
    print("Using convenience function to create USEtox input file...")
    
    # This does everything in one step: load template, populate, and export
    usetox_result = create_usetox_input_from_episuite(
        episuite_df=sample_df,
        output_path=output_file
    )
    
    print(f"✅ Successfully created {output_file}")
    print("📊 File contains populated USEtox template ready for use!")
    
except Exception as e:
    print(f"Error creating USEtox file: {e}")
    print("This is expected if the USEtox template file is not in the expected location.")
    
# Alternative: Manual export if you have the usetox_input object
try:
    if 'usetox_input' in locals() and usetox_input.populated_df is not None:
        usetox_input.export_to_excel(
            output_path="manual_" + output_file,
            include_headers=True,
            include_original_template=True
        )
        print(f"✅ Also created manual_{output_file} with original template included")
except Exception as e:
    print(f"Manual export error: {e}")

In [ ]:
## Advanced USEtoxInput Usage

# You can also add experimental data and manual chemicals
print("🔬 Advanced usage examples:")

# Example: Adding experimental data (if you have experimental values)
experimental_data = {
    '50-00-0': {  # Formaldehyde
        'Sol25': 400.0,  # g/L (experimental water solubility)
        'Data source': 'Experimental + PyEPISuite'
    }
}

# Example: Adding a chemical manually
if 'usetox_input' in locals():
    try:
        # Add a chemical with custom properties
        manual_properties = {
            'MW': 78.11,
            'KOW': 100.0,  # Not log KOW, actual KOW value
            'Sol25': 1.78,  # g/L
            'Data source': 'Manual Entry'
        }
        
        row_added = usetox_input.add_chemical_manually(
            cas='71-43-2',
            name='Benzene',
            properties=manual_properties
        )
        
        print(f"✅ Added Benzene manually at row {row_added}")
        
        # Update with experimental data
        usetox_input.populate_from_experimental_data(experimental_data)
        print("✅ Updated with experimental data")
        
    except Exception as e:
        print(f"Error in advanced usage: {e}")

print("\n📋 Key features of USEtoxInput class:")
print("• Automatic unit conversions (log KOW → KOW, mmHg → Pa, mg/L → g/L)")
print("• Data validation with warnings and errors")
print("• Summary statistics generation") 
print("• Excel export with custom formatting")
print("• Integration with experimental data")
print("• Manual chemical addition")
print("• Template compatibility with USEtox software")

In [ ]:
## 🆕 New Enhanced Features

# The enhanced USEtoxInput class now includes:
# 1. Comprehensive Excel column mapping
# 2. Experimental data prioritization over estimated values
# 3. Extended property mapping from EPI Suite results

print("🔍 Demonstrating new enhanced features:")

try:
    # Create USEtoxInput instance to show new features
    usetox_enhanced = USEtoxInput()
    
    # Show Excel column mappings for key properties
    print("\n📊 Excel Column Mappings:")
    key_properties = ['CAS RN', 'Name', 'MW', 'KOW', 'Koc', 'KH25C', 'Pvap25', 'Sol25', 'T1/2A']
    for prop in key_properties:
        excel_col = usetox_enhanced.get_excel_column_letter(prop)
        print(f"  {prop:<15} → Excel Column {excel_col}")
    
    # Demonstrate experimental data priority
    print("\n🧪 Experimental Data Priority System:")
    print("When both experimental and estimated data are available:")
    
    for prop, sources in usetox_enhanced.EXPERIMENTAL_PROPERTY_PRIORITY.items():
        print(f"  {prop}: {' > '.join(sources)}")
        print(f"    (Experimental data takes priority over estimated)")
    
    # Show expanded property mapping
    print(f"\n📈 Extended Property Mapping:")
    print(f"  Total EPI Suite properties mapped: {len([v for v in usetox_enhanced.EPISUITE_TO_USETOX_MAPPING.values() if v])}")
    print(f"  Total Excel columns mapped: {len(usetox_enhanced.EXCEL_COLUMN_MAPPING)}")
    
    # Show new analysis capabilities
    print(f"\n🔧 New Analysis Methods:")
    print("  • get_excel_column_mapping_summary() - Map properties to Excel columns")
    print("  • get_data_source_analysis() - Analyze experimental vs estimated data")
    print("  • print_column_mapping() - Display formatted column mapping")
    print("  • print_data_source_summary() - Show data source statistics")
    
except Exception as e:
    print(f"Demo error (expected if template not found): {e}")

print("\n✨ Enhanced USEtoxInput provides:")
print("  ✅ Automatic experimental data prioritization")  
print("  ✅ Complete Excel column letter mapping")
print("  ✅ Expanded EPI Suite property coverage")
print("  ✅ Detailed data source tracking")
print("  ✅ Comprehensive analysis and reporting")

## 🎯 Complete USEtox Export Example

This example demonstrates the complete workflow from searching chemicals to exporting USEtox-ready Excel files:

In [ ]:
# Complete USEtox Export Example
# This example shows the full workflow from chemical search to USEtox Excel export

print("🧪 PyEPISuite → USEtox Complete Workflow Example")
print("=" * 55)

# Step 1: Define chemicals of interest
target_chemicals = {
    "50-00-0": "Formaldehyde",     # Common industrial chemical  
    "67-56-1": "Methanol",        # Solvent
    "100-41-4": "Ethylbenzene"    # Industrial chemical
}

cas_list = list(target_chemicals.keys())
print(f"\n📋 Target chemicals ({len(cas_list)}):")
for cas, name in target_chemicals.items():
    print(f"  • {name} (CAS: {cas})")

# Step 2: Search and get predictions
print(f"\n🔍 Searching EPI Suite database...")
try:
    # Search for chemicals
    chemical_ids = search_episuite_by_cas(cas_list)
    found_ids = [id_obj for id_obj in chemical_ids if id_obj.cas in cas_list]
    print(f"✅ Found {len(found_ids)} chemicals in database")
    
    # Submit for predictions
    print(f"⚗️  Getting EPI Suite predictions...")
    epi_results, ecosar_results = submit_to_episuite(found_ids)
    print(f"✅ Received predictions for {len(epi_results)} chemicals")
    
    # Convert to DataFrame
    print(f"📊 Converting to DataFrame...")
    target_df = episuite_to_dataframe(epi_results)
    print(f"✅ Created DataFrame: {target_df.shape[0]} chemicals × {target_df.shape[1]} properties")
    
    # Display key information
    print(f"\n📈 Chemical Data Summary:")
    print("-" * 30)
    
    key_cols = ['name', 'molecular_weight', 'log_kow_estimated', 'water_solubility_logkow_estimated', 'atmospheric_half_life_estimated']
    display_cols = [col for col in key_cols if col in target_df.columns]
    
    for idx, row in target_df.iterrows():
        print(f"\n{row['name']} (CAS: {row['cas']}):")
        if 'molecular_weight' in row:
            print(f"  MW: {row['molecular_weight']:.1f} g/mol")
        if 'log_kow_estimated' in row:
            print(f"  Log Kow: {row['log_kow_estimated']:.2f}")
        if 'water_solubility_logkow_estimated' in row and pd.notna(row['water_solubility_logkow_estimated']):
            print(f"  Solubility: {row['water_solubility_logkow_estimated']:.2f} mg/L")
        if 'atmospheric_half_life_estimated' in row and pd.notna(row['atmospheric_half_life_estimated']):
            print(f"  Atm. Half-life: {row['atmospheric_half_life_estimated']:.1f} hours")
    
except Exception as e:
    print(f"❌ Error in data retrieval: {e}")
    # For demo purposes, we'll continue with existing data
    target_df = epi_df.head(3)  # Use first 3 chemicals from earlier results
    print(f"📝 Using demo data with {len(target_df)} chemicals for USEtox export demo")

print(f"\n✅ Ready for USEtox export with {len(target_df)} chemicals!")

In [ ]:
# Step 3: Export to USEtox Format
print("📤 Exporting to USEtox Excel format...")

# Add experimental data for demonstration (optional)
experimental_data = {
    "50-00-0": {  # Formaldehyde
        "Sol25": 400.0,  # g/L (experimental water solubility)
        "Data source": "Experimental + PyEPISuite"
    }
}

# Define output file
output_file = "tutorial_usetox_export.xlsx"

try:
    # Import the USEtox functionality
    from pyepisuite.usetox_input import create_usetox_input_from_episuite
    
    print("🔧 Creating USEtox-compatible Excel file...")
    
    # Create USEtox input file using the convenience function
    usetox_result = create_usetox_input_from_episuite(
        episuite_df=target_df,
        output_path=output_file,
        experimental_data=experimental_data
    )
    
    # Display success information
    print(f"\n🎉 USEtox Excel file created successfully!")
    print(f"📁 File: {output_file}")
    
    # Show export statistics
    stats = usetox_result.get_summary_statistics()
    print(f"\n📊 Export Statistics:")
    print(f"  • Chemicals exported: {stats['total_chemicals']}")
    print(f"  • Properties populated: {stats['properties_populated']}")
    print(f"  • Missing values: {stats['missing_values']}")
    
    # Show Excel column mapping for key properties
    print(f"\n🗂️  Key USEtox Properties → Excel Columns:")
    key_usetox_props = ['CAS RN', 'Name', 'MW', 'KOW', 'Sol25', 'Pvap25', 'KH25C', 'T1/2A', 'Koc']
    for prop in key_usetox_props:
        excel_col = usetox_result.get_excel_column_letter(prop)
        if excel_col:
            print(f"  {prop:<8} → Column {excel_col}")
    
    # Data source analysis
    source_analysis = usetox_result.get_data_source_analysis()
    print(f"\n🔍 Data Sources:")
    for source_type, count in source_analysis.items():
        print(f"  • {source_type}: {count}")
    
    # Show validation results
    validation = usetox_result.validate_data()
    if validation['warnings']:
        print(f"\n⚠️  Data Validation Warnings:")
        for warning in validation['warnings'][:3]:  # Show first 3
            print(f"  • {warning}")
        if len(validation['warnings']) > 3:
            print(f"  ... and {len(validation['warnings']) - 3} more")
    
    print(f"\n✨ USEtox Features Applied:")
    print(f"  ✓ Automatic unit conversions (log Kow → Kow, mmHg → Pa)")
    print(f"  ✓ Experimental data priority over estimated values")
    print(f"  ✓ Complete Excel column mapping")
    print(f"  ✓ Data validation and quality checks")
    print(f"  ✓ Ready for USEtox software import")
    
except ImportError:
    print("⚠️  USEtox export functionality not available (module not found)")
    print("📝 Exporting basic DataFrame to Excel instead...")
    
    # Fallback: basic DataFrame export
    target_df.to_excel("tutorial_basic_export.xlsx", index=False)
    print(f"✅ Basic Excel export completed: tutorial_basic_export.xlsx")
    print(f"📋 Contains {len(target_df)} chemicals with {len(target_df.columns)} properties")
    
except Exception as e:
    print(f"❌ USEtox export error: {e}")
    print("📝 This might be due to missing USEtox template file")
    
    # Show what the export would contain
    print(f"\n📋 Data that would be exported to USEtox format:")
    usetox_mappable_cols = ['cas', 'name', 'molecular_weight', 'log_kow_estimated', 
                           'water_solubility_logkow_estimated', 'vapor_pressure_estimated',
                           'henrys_law_constant_estimated', 'atmospheric_half_life_estimated',
                           'log_koc_estimated', 'bioconcentration_factor']
    
    available_cols = [col for col in usetox_mappable_cols if col in target_df.columns]
    print(f"  ✓ Available properties: {len(available_cols)}")
    for col in available_cols[:8]:  # Show first 8
        print(f"    • {col}")
    if len(available_cols) > 8:
        print(f"    ... and {len(available_cols) - 8} more")

print(f"\n🎯 Workflow Complete!")
print(f"📚 Next steps: Import the Excel file into USEtox software for impact assessment")